### ISSUE TITLE
Teams Classic - Bots not working

### ISSUE THREAD

**Issue by gykung** [MicrosoftDocs/msteams-docs#10054]
I have a teams chatbot built using Python SDK 4, served on ngrok, at the "Test your bot in Teams" phase, without uploading of manifest (we follow "test-your-bot-in-teams" at https://learn.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0#test-your-bot-in-teams).

The bot has suddenly stopped being accessible on Teams Classic on "Microsoft Teams Version 1.6.00.29964 (32-bit). It was last updated on 10-Nov-23."

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/70024742/d1177406-a405-453f-9166-902d9067ca78)

Separately, we've faced the same issue with the **New** Teams since 1+ months ago: https://github.com/MicrosoftDocs/msteams-docs/issues/9743

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
This behavior is by design in New Teams Client. 

To interact with bot via azure portal, you need to have side loading of apps enabled in the tenant.
For classic Teams also, same behavior will be implemented but we don't have exact ETA to share.

Reference docs: 
**Enable custom Teams apps and turn on custom app uploading:** https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading

**Upload your app in Teams:** https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload

Thanks!!

**Comment by gykung** [comment]
Resolved, see solution at https://github.com/MicrosoftDocs/msteams-docs/issues/9743

I suggest that the following documentation to be updated: https://learn.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0#test-your-bot-in-teams

**Comment by gykung** [comment]
Resolved, see solution at https://github.com/MicrosoftDocs/msteams-docs/issues/9743

I suggest that the following documentation to be updated: https://learn.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0#test-your-bot-in-teams
