### ISSUE TITLE
Teams for Mac - Badge Application Icon

### ISSUE THREAD

**Issue by bionemesis** [MicrosoftDocs/msteams-docs#10050]
On the New Teams for Mac, the badge application icon doesn't work to signify that there is an unread notification. This continues to work fine on the classic version.
![CleanShot 2023-12-01 at 07 01 32](https://github.com/MicrosoftDocs/msteams-docs/assets/3002979/aa4c956b-9fc5-4303-b715-777221e13b17)

**Comment by Meghana-MSFT** [comment]
This issue seems to be related to Teams product. We will add appropriate tag. For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum).
