### ISSUE TITLE
Buttons on adaptive cards are broken on Android

### ISSUE THREAD

**Issue by sschoeb** [MicrosoftDocs/msteams-docs#10097]
Since a few days (I expect since the update to version 1416/1.0.0.2023213504) our users report issues with the android teams app. 

Whenever they click on a button on an adaptiv card of our bot, the text of the button is sent to the bot (visible in the chat), but no answer is given by the bot. Our logs show, that the call never made it to our backend. 

Here an example video showing a button click and typing the same command:
https://github.com/MicrosoftDocs/msteams-docs/assets/2493698/685f31cb-0e95-443e-92db-e9cf6f48eba2

The bot does work totally fine on the latest desktop client, so I expect it to be an issue of the latest android release. 
As this destroys the bot on all android devices, I would consider this an urgent issue!

**Comment by sueess** [comment]
We got several complains from android user of our Bot. Issue is independent from Android versions/devices. We did not find a device, where the buttons are still working. Thanks for a fast fix.

**Comment by Prasad-MSFT** [comment]
@sschoeb - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
Hi @sschoeb , @sueess - We tried to repro this issue using below sample (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-all-cards/csharp), however it works fine both in MS Teams Desktop/Web and Android client. 
On clicking on button, it sends the required text and returns response as expected.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/f7a240e3-02f0-419c-9742-ebac9feefe9a)


Tested on Android 11
MS Teams Version:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/49b6b0c9-763f-4ce7-be86-d8991acd878c)

**Comment by sschoeb** [comment]
@Prasad-MSFT thanks for checking this out. 

We still run into the mentioned problem above. We have checked other bots and we can reproduce the issue there as well. 

You can reproduce the issue by installing the App "Micromate". There you will see that the buttons do not work on your mobile. For testing you could join the demo organization using the code "D8A5-77B9-C796-D7B0".

**Comment by sschoeb** [comment]
@Prasad-MSFT I used your sampel application and with a super small adjustment I can see the issue described above. 

If you change the action of the collectionCard to this:
```
"actions": [
    {
      "type": "Action.Submit",
      "title": "DoIt",
      "data": {
        "msteams": {
          "type": "messageBack",
          "displayText": "DoIt",
          "value": {
            "sendText": "DoIt"
          }
        }
      }
    }
  ]
```
As soon as you have the type "messageBack", it does not work anymore on the android client. But as this is officially documented [here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json) I would definitely expect that to work!

**Comment by Prasad-MSFT** [comment]
@sschoeb - We are able to repro this issue using `messageBack` action type in adaptive card. It does work in Desktop/Web client but doesn't work in mobile clients. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 
Thanks!

**Comment by sschoeb** [comment]
@Prasad-MSFT thanks for the confirmation. 

As this is a very severe bug which basically destroys a lot of bots on mobile clients, it would be great to have at least a bit of a time estimation what we have to expect on this? Is this something considered important for the dev team or just a bug they will look at whenever they have time?

**Comment by Prasad-MSFT** [comment]
@sschoeb - We understand this. Considering the number of users getting affected by this, we have increased the severity of the bug. However, currently we don't have an exact ETA to share. As soon as we get any info from engineering team, we will update in this thread.
Thanks!

**Comment by ricardo-serviceaide** [comment]
I am having exatcly the same error here. At least 3 of my clients reporting that on Android versions. iOS and Web is working fine.
![Imagem do WhatsApp de 2023-12-22 à(s) 13 38 57_a29717e4](https://github.com/MicrosoftDocs/msteams-docs/assets/114750308/98f07a3c-9c2b-4216-893d-b02f319c7002)

**Comment by Prasad-MSFT** [comment]
Hi @ricardo-serviceaide - We have informed engineering team about multiple reports on the issue. Currently we don't have any update to share. Once we get further info, we will share in this thread. Thanks!

**Comment by sschoeb** [comment]
@Prasad-MSFT Since around one month now, all our bot users are blocked on android because of this bug. There is no workaround but just a broken product. And as @ricardo-serviceaide stated we are not the only one having an unusable bot now. Is there any update?

**Comment by DenisSadokha** [comment]
Hi @sschoeb how you styling buttons from action card in adnroid app? I cant do it. I ovveride  <item name="adaptiveInlineAction">@style/adaptiveInlineAction</item> but its not working

**Comment by elknoblich** [comment]
<div align="justify">
 <p>
@sschoeb, hello. I have found a workaround, but there are a few limitations. For whatever reason, buttons, Adaptive Submit Actions when we are using Adaptive Cards, which use the "messageBack" property do not work on Android anymore. Please look at the simplified C# codes below.
 </p>
 <p>
You can actually know which operating system the client is using through their turn context whenever they send a message as the client's operating system is the platform property. In our case, it will be "Android". Unfortunately, it does not seem like you can access this property on other occasions. For an example, when you continue a conversation asynchronously, the entities are null. Therefore, in my original code, I saved it as a global string, which is overwritten whenever the client sends a message.
 </p><code>protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
{
    (irrelevant code)
    ConfigureGlobalVariables(turnContext);
    (irrelevant code)
}</code>
<br><br>
<code>private void ConfigureGlobalVariables(ITurnContext turnContext)
{
    (irrelevant code)
    GlobalVariables.OperatingSystem = turnContext.Activity.Entities?.FirstOrDefault(x => 
    x.Properties.ContainsKey("platform"))?.Properties["platform"]?.ToString();
    (irrelevant code)
}</code>
<p>
<br>
Now that we know which operating system the client is using, we can create specific buttons: those which use the "messageBack" property and those which do not use the "messageBack" property.
</p><code>public AdaptiveSubmitAction ProcessAdaptiveSubmitAction(string label, string value)
{
    if (GlobalVariables.OperatingSystem == "Android")
    {
        return new AdaptiveSubmitAction
        {
            Title = label,
            Data = new Dictionary&ltstring, string&gt
            {
                { "Value", value }
            }
        };
    }
    else
    {
        return new AdaptiveSubmitAction
        {
            Title = label,
            DataJson = JsonSerializer.Serialize(new Dictionary&ltstring, object&gt
            {
                { "msteams", new Dictionary&ltstring, string&gt
                    {
                        { "type", "messageBack" },
                        { "text", value },
                        { "displayText", label }
                    }
                }
            })
        };
    }
}</code>

<p><br>
Since the button which does not use the "messageBack" property does not automatically sets the text of the turn context, we need to set it through the "Value" key we have created.
</p><code>private void ProcessText(ITurnContext turnContext)
{
   (irrelevant code)
   if (activityValue.ContainsKey("Value"))
   {
        turnContext.Activity.Text = activityValue.SelectToken("Value").ToString();
    }
   (irrelevant code)
}</code>

<p><br>
However, while this solution does indeed work, it has its limitations: the buttons are not automatically renewed if the client decides to switch between operating systems and all the extra functionalities brought by the "msteams" properites, such as "displayText", are unavailable. This means that if the client is using the bot on the desktop app and then decides to switch to the Android app, the buttons left are still buttons which use the "messageBack" property. Therefore, they will not work if the client clicks on them on their Android, which means that they will have to type a massage in order for the operating system variable to be updated. After that, all buttons will work.
</p>
<p>
I hope this helps and that you can adapt this to your code. The main point is that you can indeed know which operating system the client is using and adapt the buttons in case they are using Android.
</p>
</div>

**Comment by sschoeb** [comment]
@elknoblich Thank you very much. This looks like at least an idea we have to check if we can get some basics back to work as long as @Prasad-MSFT or microsoft in general does not provide a fix for this issue. 

@Prasad-MSFT A rough timeline would be helpful.. implementing these changes to have a fix available in 2 weeks would be absolutely useless. But if you see that there are 100 other issues which are more important for the devs, then I think we cannot expect a fix for this soon right?

**Comment by elknoblich** [comment]
<div align="justify">
<p>
@sschoeb, you are most welcome! Since this problem is actually really severe as it literally makes the product one hundred percent useless, for Android users, I was surprised that I at least a workaround had not been posted yet. If you would like, I would be willing to talk in private with you to show my actual code with more details, not just this simplified version.
</p>
</div>

**Comment by Prasad-MSFT** [comment]
As its impacting number of developers, keeping the urgency in mind we have raised an ICM for this issue today and concerned team is looking into it. We will inform you once we have further update. 

Thanks!

**Comment by sueess** [comment]
Any update on this one?

**Comment by Jocelynncanzoneri** [comment]
Can anyone tell me why when I fill out an application it allows me to fill
out everything and after I put my social it freezes and won't finish.
Please check on this and fix it you can.  I'm missing deadlines.

Thank you
Jocelynn Canzoneri

**Comment by elknoblich** [comment]
<div align="justify">
<p>
 @Prasad-MSFT, I would like to add that we also cannot send files to a bot on Android. The files which are attached and sent are not recognized in <code>turnContext.Activity.Attachments</code>. Unlike the original issue, there is no workaround. I assume that there are other problems happening with the Android version.
</p>
</div>

**Comment by Prasad-MSFT** [comment]
@sschoeb , @ricardo-serviceaide , @sueess - The issue seems to be fixed. We verified with below MS Teams version in Android device. Please do verify.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/1e791022-33b2-48a8-98c7-602e64dafea5)

**Comment by Jocelynncanzoneri** [comment]
Explain this in normal conversation please so I can respond.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. 

Thanks!
