### ISSUE TITLE
Can I have WebRTC web apps embeded in Microsfot Teams?

### ISSUE THREAD

**Issue by kklitest** [MicrosoftDocs/msteams-docs#10333]
I want to add a calling web app in Microsoft Teams, in order to make calls on a 3rd party platform.

Can I integrate a web app to MSFT Teams, that would have WebRTC capabilities, and access to the microphone and camera of the PC?

For example, using these methods here: https://learn.microsoft.com/en-us/microsoftteams/platform/overview , Personal Apps or Tabs (and iframe in a Tab, that can do WebRTC?)

**Comment by ChetanSharma-msft** [comment]
Hello @kklitest - Thanks for raising your query.
Yes, you can integrate any web application inside a Teams tab application.

You can create a person or configurable tab: 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs?tabs=desktop%2Cdesktop1%2Cpersonal

You can refer below documentation for device permissions:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/browser-device-permissions

If you have implemented any authentication, it won't work due to IFrame, so you can implement Tab SSO:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview

Also, please add all the validDomains properly in Teams application manifest.json.
