### ISSUE TITLE
Unable to Post Messages in Teams Channel Using Graph API

### ISSUE THREAD

**Issue by adityasomann** [MicrosoftDocs/msteams-docs#10341]
I have been trying to use the Microsoft Graph API to send messages to various Teams channels from C# and PHP code.

I have configured a **Microsoft Azure Entra ID application** and given it the proper credentials according to this [documentation ](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http). I have downloaded the latest version of the Graph API for both C# and PHP and using it in the client-side application I am developing.

I am able to create the channels in Teams and am able to get the teams-id and channel-id, but when I send a POST request to send a message, it fails with the below error:

`"Message POST is allowed in application-only context only for import purposes. Refer to https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams for more details."
` 

I am getting the same error from both the C# and the PHP code. 

Just a note: Using a channel webhook works just fine when sending messages from the PHP side.

Screenshot of Permissions:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/32226028/e8903754-8f20-41ac-b48d-ecf5791b5cbd)

`Authentication Method: ClientSecretCredential`

Thank You!!!

**Comment by Prasad-MSFT** [comment]
Hi @adityasomann - This error messages indicates that you are trying to send a message using the Microsoft Graph API in an application-only context, which is only allowed for import purposes. To send messages to Teams channels using the Graph API, you need to use a user context instead.
https://learn.microsoft.com/en-gb/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=http
You need to modify your code to authenticate as a user instead of using application-only authentication.
