### ISSUE TITLE
Unable to create Azure Bot using M365 Developer Account

### ISSUE THREAD

**Issue by xib** [MicrosoftDocs/msteams-docs#10856]
### Steps to reproduce

I am following this turorial [Create Teams conversation bot](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-teams-conversation-bot.yml) using a M365 Developer Account as [described here](https://github.com/MicrosoftDocs/msteams-docs/blob/8e4eb5adc4c57bd74167b97efe4e702f13bc3f38/msteams-platform/sbs-teams-conversation-bot.yml#L38C51-L38C124)
However, upon reaching to [Create your bot](https://github.com/MicrosoftDocs/msteams-docs/blob/8e4eb5adc4c57bd74167b97efe4e702f13bc3f38/msteams-platform/sbs-teams-conversation-bot.yml#L114) step, I am not able to create an Azure Bot. 

When select Azure Bot and click Create, I am presented with this page:
<img width="1273" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/371867/48336130-3a96-4db8-90aa-0668ead125cf">

I think it could be due to: the M365 developer program sets up a developer Azure Active Directory (AAD) tenant, but it does not include an Azure subscription. Is it correct? If yes, the tutorial leads reader to a wrong step. Otherwise, I may miss a step somewhere along the way. Would anyone be able to help?
 

### Expected behavior

Create an Azure Bot page should display.

### Actual behavior

Welcome to Azure! page displayed with options to subscribe to Azure.
However, none of the options would work since I am accessing using M365 Developer Account as instructed in the first step.

### Error details

Not able to create Azure bot.

**Comment by Prasad-MSFT** [comment]
Hi @xib - Yes, you are correct in your assumption. The issue you are facing while trying to create an Azure Bot using your M365 Developer Account could be due to the fact that the M365 developer program sets up a developer Azure Active Directory (AAD) tenant, but it does not include an Azure subscription by default.
To create an Azure Bot, you need an Azure subscription to provision Azure resources to host your Teams app. If you do not have an Azure subscription, you will not have the necessary permissions to create an app in Azure Active Directory, which is required to create the bot.

Ref:
1.https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app
2. https://learn.microsoft.com/en-gb/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned

**Comment by xib** [comment]
Hi @Prasad-MSFT, thanks for the clear explanation. 
I wish the Prerequisites on M365 developer account to be clearer to avoid this. Thanks.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
