### ISSUE TITLE
Iframe is not displaying pdf

### ISSUE THREAD

**Issue by rajvaghela23** [MicrosoftDocs/msteams-docs#10887]
### Type of issue

Feature doesn't work (bug)

### Feedback

We are using the following code to display a PDF in an iframe. 

`<iframe id="pdfiframe" class="hide" name="pdfiframe" title="PDF" frameborder="0" width="100%" height="900" scrolling="auto"></iframe>`

We are calling this function to get the PDF rendered in the above iframe code. 
```
function ShowPDFInIframe(obj, orderId = 0) {
    var url = $(obj).attr("url");
    if (url != "") {
        $.ajax({
            type: "POST",
            url: rootPath + "/PDFController/LoadPdfInRefereceTab?documentURL=" + url,
            success: function (data) {
                debugger;
                var iframe = $("#pdfiframe")[0];
                iframe.src = data;
            }
        });
    }
}
```
When we click on a PDF icon in the Microsoft Teams App, it displays a blank screen. This is a screenshot from Teams of when we open the application in a web browser.  

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/318892/492fa95d-048e-4b36-9689-d733de5aa279)

We followed this link to implement the solution but we are still getting the same error.

[https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements](url)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tab-requirements.md

### Author

@surbhigupta

### Document Id

7037e9c7-f501-5b70-8acf-1f004a06289b

**Comment by Prasad-MSFT** [comment]
@rajvaghela23 - We tried to repro this issue and are also getting same error as below:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/7f5a3b57-cfd8-4dbb-89c2-8f0f4f1b35ea)

We are discussing this internally and we will get back to you once we find any resolution.


Thanks!

**Comment by Prasad-MSFT** [comment]
**Update:**

We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @rajvaghela23 - We got update from engineering team that the behavior is currently by design. 
Teams renders embedded apps in sandboxed iframes to keep our users safe. Sandboxed iframes do not support plugins which are required to render PDF files. 

For SharePoint-hosted PDF files, the app can use the app.openLink API to launch a deep link and have Teams render the file: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#generate-deep-link-to-a-file-in-a-channel

For other PDF files, the app should use window.open to render the file in the user's default browser.
