### ISSUE TITLE
deeplink to group chat

### ISSUE THREAD

**Issue by CodeABao** [MicrosoftDocs/msteams-docs#11119]
### Steps to reproduce

Hi there, I want to develop a feature that let user click a link to start a chat with multiple users.  the link like below:

https://teams.microsoft.com/l/chat/0/0?users=AdeleV@7zwf5m.onmicrosoft.com,admin@7zwf5m.onmicrosoft.com,uatuser1@7zwf5m.onmicrosoft.com&topicName=ShareInfo

### Expected behavior

my thought is the three users can in one group, but i found they create 3 groups. it's a bug or by design?

### Actual behavior

create 3 groups

**Comment by Meghana-MSFT** [comment]
@CodeABao - We checked this at our end by pasting a deeplink to chat in browser and it is working fine. It created single group chat with 3 users.

Deeplink used : https://teams.microsoft.com/l/chat/0/0?users=admin@mxxxxxxxxxxxx.onmicrosoft.com,meganb@mxxxxxxxxxxxx.onmicrosoft.com,irvins@mxxxxxxxxxxxx.onmicrosoft.com&topicName=ShareInfo

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/d823468d-8d8e-4164-982a-809f3ea40bc9)

Could you please let us know if you are facing this issue in new/classic Teams? In Teams web/Desktop/mobile clients? Please let us know how you are executing the deeplink so that we can have a repro of this issue locally.
