### ISSUE TITLE
Bot ownership transfer from dev portal is not mentioned in the documentation

### ISSUE THREAD

**Issue by v-rajimandal** [MicrosoftDocs/msteams-docs#11267]
### Type of issue

Missing information

### Feedback

As per the [documentation ](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)transferring the bot ownership from one user to another user is not present. Could you please update the same.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/manage-your-apps-in-developer-portal

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md

### Author

@surbhigupta

### Document Id

c2ab90ad-0989-85f5-6b10-8ef631252e5c

**Comment by Prasad-MSFT** [comment]
Hi @v-rajimandal , could you please let us know what exactly you want to add in this document? Because we can see there is a [section](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/manage-your-apps-in-developer-portal#advanced) where it is explained how the Administrator role has the permissions, such as updating an app's configuration, adding or removing owners, and deleting an app.

**Comment by v-rajimandal** [comment]
Hi @***@***.***>,

In the document has mentioned how to transfer app ownership not the BOT in bot management.
I can give you some context about requirement:
Cx has two users, user A and user B. User A developed a bot in Teams Dev portal. Then plan to transfer the bot ownership to user B.
User B can see the bot "PSAbot" with icon in Apps: Developer Portal (microsoft.com) But when he redirects to bots (Bot management), He can't see the bot.
For your reference, please see the screen shot of Bot Management.
***@***.***


Regards,
Rajiv Mandal
Email: ***@***.******@***.***>
Active Hours: 8AM - 5:30PM IST(UTC+5.30)

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here?
