### ISSUE TITLE
Missing command from TeamsFx-CLI article

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/msteams-docs#11578]
### Type of issue

Missing information

### Feedback

There is an "m365" command in the CLI. It is not mentioned in this article. 

![image](https://github.com/user-attachments/assets/642034d5-8eab-4787-8ec6-47a6e5011804)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-cli?pivots=version-three#teamsapp-uninstall

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/Teams-Toolkit-CLI.md

### Author

@MuyangAmigo

### Document Id

9821a370-031a-b977-6cbd-c575ea3ad21f

**Comment by Prasad-MSFT** [comment]
Thanks @Rick-Kirkham for raising your query.

Hi @surbhigupta12, could you please help here to update the document as suggested?

**Comment by Rick-Kirkham** [comment]
@v-ramyas5 I don't see how to sideload unless `m365` is used.

**Comment by v-ramyas5** [comment]
Hi @Rick-Kirkham,
Thanks for sharing the observation. Analyzing the usage of m365 in the shared scenario. Will get back on this soon.

**Comment by v-ramyas5** [comment]
Hi @Rick-Kirkham,
We observed that the [article](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/convert-xml-to-json-manifest) is outdated and the sideloading command must be updated.
![image](https://github.com/user-attachments/assets/6c7a8fef-ff53-4bf2-a8f4-cf29af7f983d)
From:
npm install -g @microsoft/teamsfx-cli
teamsfx m365 sideloading --file-path <relative-path-to-zip-file>

To:
npm install -g @microsoft/teamsapp-cli
teamsapp install --file-path <path-to-zip-file>

We confirmed the commands with the Toolkit team. Since we do not have access to the article in add-in repo, request your support in updating the commands.

Thank you.

**Comment by Prasad-MSFT** [comment]
Hi @Rick-Kirkham , could you please help creating a documentation issue in `add-in` repo and link to this issue?
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/convert-xml-to-json-manifest#sideload-with-the-teams-toolkit-cli-command-line-interface

**Comment by Rick-Kirkham** [comment]
> Hi @Rick-Kirkham , could you please help creating a documentation issue in `add-in` repo and link to this issue? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/convert-xml-to-json-manifest#sideload-with-the-teams-toolkit-cli-command-line-interface

I'm tracking this work in an ADO item.

**Comment by Rick-Kirkham** [comment]
This is fixed in the source and will publish today.
