### ISSUE TITLE
shareToMicrosoftTeams is not defined

### ISSUE THREAD

**Issue by vladschiop** [MicrosoftDocs/msteams-docs#1167]
I am trying to dynamically render the Share Button, but it seems that shareToMicrosoftTeams is not defined in the launcher script. Is there any other resource that I have to reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5964e0a9-bba0-c5a3-8099-f3845037726c
* Version Independent ID: 24565c3b-2bb5-2482-a6c7-7b1f62e38abb
* Content: [Share to Teams embedded button - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams?view=msteams-client-js-latest#feedback)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/share-to-teams.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by vladschiop** [comment]
Update: The problem was that the script was not loaded at the point when I was trying to call renderButtons.

**Comment by Gousia-MSFT** [comment]
@vladschiop Were you able to solve the issue? What is the script version you are using?

**Comment by pmeripe** [comment]
How can I share to an individual or multiple users?

**Comment by Gousia-MSFT** [comment]
@pmeripe Using shareToTeams you can share the link directly to a person. Are you facing any issues here? Could you please elaborate on what exactly you are trying to achieve?

**Comment by pmeripe** [comment]
@Gousia, I would like to share current page link with teams user from SharePoint classic page. At present I can share with Team or a channel. Please suggest the fix.

**Comment by paulconlin** [comment]
I'm actually having this issue as well, and seeing a few different things happen. I made a codepen here that has the script included in the head and shareToMicrosoftTeams is never defined - 

https://codepen.io/paulconlin/pen/VwYpbym

Was also seeing this on our site - 
![MicrosoftTeams-image (44)](https://user-images.githubusercontent.com/10995964/71215395-37c2ef80-227d-11ea-8878-53bf727aa0c6.png)

and then this error in safari 

![MicrosoftTeams-image (45)](https://user-images.githubusercontent.com/10995964/71215413-47423880-227d-11ea-855b-534f7a4fcca1.png)

We currently pulled the integration from production as it would sometimes result in a blank white page in safari.

**Comment by paulconlin** [comment]
Any update on this?

**Comment by radicalapps** [comment]
Just discovered this issue too. This used to work. Unfortunately I'm not sure when it stopped working.

It appears that using the instructions at this page: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams, shareToMicrosoftTeams is not defined. 

Looking at the source of https://teams.microsoft.com/share/launcher.js, the script appears to be trying to do something different if WebPack is in use. However, the Webpack-related behaviour is not documented. 

Our solution does use Webpack, but the script is looking for shareToMicrosoftTeams to be defined in the global namespace.

Is the documentation referenced above in line with the expected behaviour, or has something changed?

**Comment by Nikitha-MSFT** [comment]
@radicalapps -Are you still facing the issue? if yes, please feel free to reopen the issue.

**Comment by radicalapps** [comment]
This issue was apparently closed with no investigation and no action. It was not a transient issues, so surely it's not correct to close.
