### ISSUE TITLE
Missing information about the permissions required to deploy

### ISSUE THREAD

**Issue by danielc-edw** [MicrosoftDocs/msteams-docs#11854]
### Type of issue

Missing information

### Feedback

There is missing information about the permissions required to Deploy using the Toolkit. For example, it should be clearly stated if you need to be a tenant Global Admin or else.

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/deploy?source=recommendations

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/deploy.md

### Author

@MuyangAmigo

### Document Id

24348657-f892-77bc-a995-2de777c21c1b

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to add the following note in the above-mentioned doc - https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/deploy?source=recommendations

"To deploy an application using the Microsoft Deployment Toolkit, you need to have an Admin role."

**Comment by Meghana-MSFT** [comment]
@danielc-edw - We reached out to engineering team regarding above issue and team has said that we don't need to have the role of a tenant/global admin to deploy an app to Azure. Could you please let us know issues you are facing during deployment due to having/not having tenant/global admin permissions.
