### ISSUE TITLE
Query topicName does not work when using msTeams Protocol

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/msteams-docs#11905]
### Type of issue

Feature doesn't work (bug)

### Feedback

If using msTeams: as the protocol handler in a deeplink that generates a chat, the query "topicName" is not recognized. It works as expected when using https: instead. In the docs i can't find a limitation for it. so it should be able to use topicName also when using  msTeams Deeplinks

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#deep-link-to-start-a-new-chat

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-link-teams.md

### Author

@v-npaladugu

### Document Id

b6687ceb-6d67-b0b7-0797-b16d14e4bd97

**Comment by sayali-MSFT** [comment]
@J-a-k-o-b ,
Thank you for your inquiry about your Teams app development issue! 
We are checking the issue. We will get back to you shortly.

**Comment by sayali-MSFT** [comment]
Hello @J-a-k-o-b ,
We have tested the scenario with msteams: and it is working fine on our end. 
Could you kindly confirm if you are attempting the same? If possible, would you mind sharing the deeplink and a short video so that we can try it on our side as well?

 Microsoft Teams version 24341.1300.3292.5164.
 
 Deeplink-msteams:/l/chat/0/0?users=joe@contoso.com,bob@contoso.com&topicName=Prep%20For%20Meeting%20Tomorrow&message=Hi%20folks%2C%20kicking%20off%20a%20chat%20about%20our%20meeting%20tomorrow
 
 Reference Document-https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#protocol-handlers-in-deep-links
 
![Screenshot 2024-12-10 173008](https://github.com/user-attachments/assets/e699eb88-5fc9-46a5-957f-756229f0d2f2)

**Comment by J-a-k-o-b** [comment]
Hi @sayali-MSFT, it seems that I've had an encoding issue with the & . Sorry about the circumstances. It works as expected.

**Comment by sayali-MSFT** [comment]
Hello @J-a-k-o-b ,
Good to hear that your issue is resolved now.

Additionally, we would appreciate it if you could share your valuable feedback via the [Microsoft Teams Developer Community Response Feedback ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3Dv4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u&data=05%7C02%7Cv-sadange%40microsoft.com%7C5b921f4e4b0745c25a9a08dd1516a8ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638689909276852350%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=7AvU4XYb2zaAdzayxu4acJoagcQOyVMaMitaSQ0V844%3D&reserved=0)link?

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
