### ISSUE TITLE
Be aware that nobody will acknowledge email sent to the "General Questions" address

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/msteams-docs#1272]
I've sent two in the last year and received no reply or acknowledgement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Send feedback - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/feedback.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by billbliss** [comment]
What "General Questions" email address are you referring to?

**Comment by StingyJack** [comment]
![image](https://user-images.githubusercontent.com/15381181/72555453-95416080-386a-11ea-9b64-51ce5fbb3304.png)
The one that you replied back to me a few days ago about, after I had sent another two messages after the ones mentioned in this.

**Comment by billbliss** [comment]
We look at all of them, but don't always reply. What is your email address or if you prefer, the subjects of the emails so we can look?

**Comment by billbliss** [comment]
Ah I know who you are, I just clicked through on your GitHub profile, your name's right there.

I'm going to re-word "General questions" to mean "General questions about the Teams developer platform" because that email address is NOT designed for general questions about Teams. We get them anyway but that's not what the email address is for.

When we do get general suggestions, we forward them to the right team but unless it's a bug, we don't reply.

The wording is not at all clear.
