### ISSUE TITLE
What is the simplest way to get UPN of a Teams User for a Bot Framework enabled Chat Bot?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/msteams-docs#1415]
Much of the tenant information comes in with each user message., The bots themselves have been explicitly added by the user or tenant administrator, implying consent, so it seems an overkill for a bot to use a second hit simply to get UPN/email ID of the user using the bot the first time. This is often necessary to identify the user.

The bot framework provides a way (var userInfo = await connector.Conversations.GetConversationMembersAsync(conversationId );) but under the hood that is also another hit.

What is the current recommended way to simply get the user UPN/Email ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c780d605-b1b2-716f-5888-503608769b5a
* Version Independent ID: 53c724f8-d9a2-4af6-6d75-ddeaef084137
* Content: [Bot API Changes for Team/Chat Members (2020 update) - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes#feedback)
* Content Source: [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/team-chat-member-api-changes.md)
* Product: **msteams**
* GitHub Login: @ojchoudh
* Microsoft Alias: **ojchoudh**

**Comment by Gousia-MSFT** [comment]
@GauravES You could get the email id of the user by [fetching the roster](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#fetching-the-roster-or-user-profile) using Bot. The other way to do it is using [Graph API to fetch user email](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http). In from.aadObjectId of the Activity object there’s the AAD Object ID of the sender; from that you can look up the email address using MS Graph provided your appId has at least User.ReadBasic permissions. The email address is not included for privacy reasons, by design.
