### ISSUE TITLE
Team-member can invite persons to team

### ISSUE THREAD

**Issue by bomski** [MicrosoftDocs/msteams-docs#1529]
We found today a security/permission bug in MS Teams. 

Steps to reproduce:

1. Create a new team as member of an existing team
2. Invite new persons via e-mail address
3. New Team created

So far so good, but the invited persons also gets added to the first team where the user is only a member and should not allowed to add new members.

We could reproduce the bug twice and the invited persons really gets the access to the team (Not so funny).

Additional Information
- The "member" user had 2 teams before creating a new team. 
- User is in both teams only member
- User didn't has "Add member" Option in User Interface

**Comment by Abhijit-MSFT** [comment]
@bomski, Thanks for reaching out. Please tell me if my steps are different from what you tried because i tried two time and both the time it was WAD.

- I am part of 3 different teams (member and not owner)
- Created new Team
- Invited new user using e-mail address
- New user accepted the invite and logged into Teams
- On my side i see that new user got added to the only Team where i had invited him
- He did not get added to the rest of the 3 Teams where I am member of the Team and not owner

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
