### ISSUE TITLE
Getting user email in message extension

### ISSUE THREAD

**Issue by ndileep** [MicrosoftDocs/msteams-docs#1574]
When a user clicks message extension in a team where the bot is not installed, the bot service gets the user's aadObjectId. Is there a way to get the user's email address using Teams APIs (without calling any Graph API)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca47e045-6669-e130-c75a-df31ab2fa3e8
* Version Independent ID: de5e719f-c97a-0fee-c83d-f6ca176191b2
* Content: [Get Team's specific context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#fetching-the-roster-or-user-profile)
* Content Source: [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/get-teams-context.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment]
@ndileep , You can fetch the user principle name from the context itself . Please follow the below the steps to get the `UPN`.
1. [Get Access Token  ](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0#get-token)
![image](https://user-images.githubusercontent.com/50989436/80070885-599ced80-8561-11ea-9d30-78b9a5789afd.png)

2. Calling the given endpoint `{{serviceUrl}/v3/conversations/{conversationID}/members}`
![image](https://user-images.githubusercontent.com/50989436/80070857-4ab63b00-8561-11ea-86a5-966e83a57b1c.png)

**Comment by liangchr** [comment]
@Trinetra-MSFT but what if the bot is not installed on the team? The user got the aadId +tenentId from a globally installed messaging extension. When I use.{{serviceUrl}/v3/conversations/{conversationID}/members} it says I can't get the information because the bot is not installed in the conversation.

**Comment by Trinetra-MSFT** [comment]
@ndileep , Did you tried fetching the user profile through [Get User](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http) Graph API? You can also retrieve the details of a particular user using their Teams user Id, UPN, or AAD Object Id. Please look at
[get single user]( https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#get-single-member-details) details.

**Comment by ndileep** [comment]
Doesn't calling the graph API requires extra permissions from the user? With just the bot token and the payload it receives from MS when the user clicks the message extension, is there a way to get user's email without asking for extra permissions? (The scenario here is that the bot is not installed in the team/1:1 channel where the user is clicking the message extension).

**Comment by liangchr** [comment]
@clearab This is a cool solution we overlooked. Thanks for the suggestion

**Comment by clearab** [comment]
If you're looking for a specific user, use the TeamsInfo.GetMember() endpoint in the newest SDK version to avoid latency issues in large teams.

**Comment by ndileep** [comment]
> Hi - You can use the just-in-time install flow to get your bot installed before trying to fetch the roster: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

Thanks @clearab, for your reply. Won't this require user to have permission to install the bot? In most of the enterprises the admin or a few members have bot install permission.

**Comment by clearab** [comment]
Yes, the user would need to have permissions to install a bot in that context. In organizations that use apps, it usually isn't _that_ locked down, but you'd definitely have some % of users that were unable to complete that process.

If you think about it however, this is exactly why you're unable to retrieve the roster of that particular context. Retrieving that roster requires someone who has been granted authority consent to your app existing, and collecting information, from that particular context.

If all you're looking for is that one user's information, and they've invoked your messaging extension then one of these things must be true (otherwise they wouldn't be seeing your messaging extension):

1. The user has your app personally installed.
2. The user is in a context where your app is already installed (group chat or team channel)

In the first case, you should already have access to the full user information. If you haven't stored it somewhere you can use the 1:1 conversation between your app and that user to call getConversationMember() to retrieve the needed information.

In the latter case, you should be able to call getConversationMember() to retrieve that particular user's information from the context the messaging extension was invoked from.

All of this is predicated on your app containing a conversational bot, as well as a messaging extension. 

One final note, please keep in mind that sometime in 2021, all getMember calls will stop returning email and UPNs: see [this article](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes)

**Comment by ndileep** [comment]
Thanks Andrew!

The scenario in our case is that the Admin installed the app as a "pinned app in the Teams app navigation bar". The app then shows up on the left navigation bar of the client and also as a message extension for all users in 1:1 and team channels. The users themselves don't have permission to install the app.

**Comment by clearab** [comment]
Ok, in that case it won't matter, as the app is already installed for them. You'll get a conversation update event of MembersAdded when that happens, that will contain the necessary information. You should store it then.

Approach number 1 above will also work.

**Comment by clearab** [comment]
You'll get one of these for every user: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#team-members-added

**Comment by ndileep** [comment]
Yes, for new members after the app installed, we can make use of the events. Looks like for existing members there is no way to get UPN without calling Graph APIs, which requires some other flow to get required permissions.

**Comment by clearab** [comment]
No, for existing users you have all the necessary information to retrieve a full Teams Channel Account. The psuedocode would be something like this:

1. On messaging extension invoke, retrieve the teams userId for that user (something like activity.recipience.from.id). This value should be stored.
2. Call CreateConversation using that user Id. Example [here](https://github.com/clearab/teamsProactiveMessaging/blob/f074be9f0377b761d62c1594ac4d090501becfd0/MessageSender.cs#L28). This get's use the necessary conversationReference. This value should also be stored.
3. Now you need a turn context in the right context (in this case the 1:1 chat between you and the user). You'll use turnConversation.Adapter.ContinueConversationAsync for this.
4. Now that you've got the right context, call getMember() to get the email.
5. Make sure you save everything so you can just validate the info occasionally (or at least asynchronously)

Use something like for the continue conversation call (not validated):

```dotnet
var member = new TeamsChannelAccount()
await turnContext.Adapter.ContinueConversationAsync(_botId, conversationReference, async (context, token) => {
    member = TeamsInfo.GetMember(context, AADId, token);
}
```

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query
