### ISSUE TITLE
Where is the REST API docs?

### ISSUE THREAD

**Issue by viperfx** [MicrosoftDocs/msteams-docs#1591]
Ive noticed a disturbing trend of the MSTeams docs focusing on their SDK and making all examples the SDK only.

This is REALLY BAD idea. Not everyone will develop in a technology stack based on the SDKs available. Even us, we use python internally but we still prefer to use the REST API and implement our own SDK.

Please add back REST API and JSON examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 293d28d8-bd82-299a-05b3-4f798e485542
* Version Independent ID: 2f747d61-5ff7-be26-d55d-fdc715f4293d
* Content: [Update and delete messages sent from your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=python#feedback)
* Content Source: [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/update-and-delete-bot-messages.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by jerry-le** [comment]
I thought the REST API is not added, but turn out it was there but removed! 
I have no ideas on why the Teams Platform did that. Please add it back.

**Comment by clearab** [comment]
Looks like this page got missed when we were adding examples. You can find them here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bot-conversations/bots-conversations#updating-messages

@laujan Can you move the JSON tabs for updating and deleting messages from the link above to this page?

**Comment by clearab** [comment]
Out of curiosity, why would you choose to implement your own SDK? I think seeing the REST calls is very helpful for both understanding and debugging, but what would the motivation for not using the Python SDK be?

**Comment by viperfx** [comment]
That's a fair question @clearab 

We developed our application back in the days when only the REST API and .NET resources were available. Node SDK followed, then python SDK followed, but I believe there were many months between those becoming available. 

We are keen to explore the python SDK more, and we are not saying we will never use it, but at the moment, it just does not make sense to drop our own SDK to use MS SDK.

I would say internally, our SDK, has things like Retry requests, timeouts, custom error handling etc. Does your SDK have all that built in? 

Our concern is also with releases and how timely they are. We are part of the TAP program, and we get access to early feature from MS Teams devs, same goes for Adaptive Cards. We want to develop against these asap.

Is there some key advantages to using your SDK over what we could implement internally with a REST API? or anything we might have missed that is implemented with the SDK? 

Cheers

**Comment by clearab** [comment]
That definitely makes sense - they Python SDK came along quite a bit after the others. Please don't take the below as a sales pitch, I think it's awesome you've built your own SDK and I'm going to guess there is a lot of things there that are specific to the way you use bots that meet your needs :). 

But to give a quick overview of the SDK:

Yes, the SDK has most of that built in, and is built to be extensible so you can plug in your own versions if you prefer. A lot of the SDK deals with four primary areas:

1. Dispatching incoming activities to well-defined activity handlers.
2. Managing state at various scopes
3. Creating & managing dialogs
4. Authentication support (both authenticating the client/bot interaction as well as support for using OAuth for user authentication)

There's a lot of other stuff like the middleware constructs, helper methods for lots of typical scenarios, help for using language recognizers like LUIS or QnA maker, and whatnot, but those 4 are the major areas I think.

As for release cadence, the SDK releases about every 2.5 months and since we onboarded Teams as a first party channel in the SDK we've kept up fairly closely to their GA schedule. We'd match that, rather than the developer preview releases, so there definitely would be a bit of a delay before full SDK support was provided (in the interim you'd have to drop down to REST, although in almost all cases this would be just creating/reading JSON payloads not sending HTTP requests as adding completely new endpoints is very rare).

Since you're in TAP, I think it might be interesting to explore a deeper comparison of our two solutions, would you be open to that?

**Comment by viperfx** [comment]
Thanks for the detailed feedback. All of that does sound great and it's
tempting to merge the SDK for us.

For sure, would love to connect. Will reach out to you.
