### ISSUE TITLE
Teams meeting ignores right channel on stereo/dual microphone devices

### ISSUE THREAD

**Issue by inks007** [MicrosoftDocs/msteams-docs#1633]
Steps to reproduce:

Use any microphone setup with two channels. Tested with:
- [ART USB Dual Pre](https://artproaudio.com/product/usb-dual-pre-project-series-two-ch-usb-pre/)
- [Behringer ULM202USB](https://www.behringer.com/Categories/Behringer/Wireless-Systems/Microphone/ULM202USB/p/P0AQE)

Teams meetings will only utilise the 1st (left) microphone channel.
When testing the 2nd microphone channel, no response is registered on the microphone VU meter under "Device Settings", nor is it transmitted to the remote users.
![image](https://user-images.githubusercontent.com/12200916/81398752-6a05b880-915c-11ea-88d2-7a90703b0a5d.png)

This is reproducible in Windows 7, Windows 10 and macOS. Tested with:
- macOS Catalinas 10.15.4, Teams 1.3.00.8663
- Windows 7 Enterprise SP1, Teams 1.3.00.12058 (64-bit)
- Windows 10 Pro 10.0.17763, Teams 1.3.00.8663 (64-bit)

In Windows, I have attempted the following:
- turning on exclusive mode
- turning off exclusive mode and forcing 2 channel as the default format
- turning off exclusive mode and forcing 1 channel as the default format

![image](https://user-images.githubusercontent.com/12200916/81369918-5f303100-9126-11ea-81c4-0c3bbb7fc2fd.png)
All exhibit the same problem.

What should be expected behaviour:
Teams downmixes the 2 microphone channels to mono

Assistance / fix appreciated, thank you.

**Comment by Subhasish-msft** [comment]
@inks007 , This is by design. The reason for not averaging the input channels is that it can create a comb filter effect, where in the extreme case, you can take two audible signals which are out of phase, average them, and then you get silence. In less extreme settings, but for the same reason, the average just does not sound as good as when selecting the best mono channel. We select the first channel (left), as for some devices that is the primary microphone, and the second channel (right) might, e.g., be facing backwards.

**Comment by inks007** [comment]
@Subhasish-msft Thanks for the reply.

The extreme case you mention would only occur if someone improperly tries to plug a powered, balanced mono microphone via adapters into a stereo 3.5mm mic input.

Proper stereo microphones don't have significant path differences to create severe out-of phase interference with mono down-mixing. Nor should they be out-of-phase, unless there is a design flaw.

With regards to speech reaching one channel at different times to another, let's take an example [Olympus ME51S](https://www.getolympus.com/us/en/stereo-microphone-me51s.html) which has condensers separated by about 35mm. If a speaker were directly facing one side of those condenser (the other facing backwards), the other side would have out-of-phase response at 4.9kHz. If these were perfect transducers recording a perfect point source, then your comb filter width would be 9.8kHz, and the next null node at 14.7kHz (9.8+4.9kHz). Whilst it is true you avoid the issue altogether by selecting only one microphone, you're losing information from a functioning right channel (e.g. second speaker).

The real issue is with dual microphone setups (e.g. one for the speaker, a second for the local audience). These present to the OS as 2 channels (the OS and the application would not be able to differentiate between a stereo microphone, or dual mono microphones). Simply dropping everything but the first channel is a waste of information. With dual/multiple mono setups, microphones are distanced from each other and thus can be mixed together without significant artifact.

Mixing multiple microphones happens commonly with videoconferencing systems.
E.g. [Olympus ME33](https://www.olympus.com.au/product/audio/accessory/mic/me33.html). These are designed to be daisy-chained 3 in a row.
Another example. [Revolabs Executive HD](https://uc.yamaha.com/getmedia/1ed715b6-1c81-4be5-9c80-1b7108ec2d5f/MN-EXEC-WIRELESS-MIC-SYSTEM-20180504-EN.pdf). These are designed for video-conferencing, typically with 4-8 microphones. They just get mixed in analog using mixers such as [this](https://www.shure.com/en-GB/products/mixers/scm800) .

Microphone systems have been slow to move over to the digital era, but we're slowly getting more conferencing grade USB Audio Class 1/2 and bluetooth devices. We need a way of utilising current stereo/dual setups, future 4-8 channel devices, and perhaps even multiple bluetooth microphone setups.

Ideally, videoconferencing software should allow selection of multiple microphone devices, e.g. [OBS](https://obsproject.com/), and down-mixing of multiple channels.

**Comment by GizmoChicken** [comment]
@inks007   I agree with you.  And I was disappointed/frustrated to learn that there is still no _easy_ way to use two XLR microphones (connected to my two channel interface) with Teams.  I say no "easy" way, because of course I could use something like JACK or Voicemeeter to route channel 2 to channel 1, but that's not "easy" for most, especially if you don't have authority to install such programs on your work computer.

My solution:  I bought a relatively inexpensive USB mixer, and use it to pan all my mics to channel 1 for use with Teams.  In my case, I opted for a Mackie ProFX10v3.  But a cheaper model, such as the Mackie ProFX6v3 (or similar) would probably work as well.  If you buy a mixer for this purpose, I suggest buying one that includes an easy way to mix direct/usb, like what's included with the  Mackie ProFX6v3 and Mackie ProFX10v3.  This will allow you to monitor yourself directly (without latency), while listening to others through USB.

@Subhasish-msft  and @Wajeed-msft  I hope that you'll add some mixing functionality to Teams, so that I won't need to use an external mixer to input multiple mics.

**Comment by noblockhit** [comment]
Ex. I'm using a steinberg Yamaha UR 22mk 2. I am connecting a microphone to the right channel, and my e-Guitar to the right one.
Teams registeres the sound coming from my pre amp, but does not transmit it. This is 1. very confusing, 2. a pretty big problem. If i switch up the slots, it's vice versa. I'd really like to have an option to just transmit both, without the cancelling. My mic is pretty high quality so there is not much use to filter anything.

**Comment by GizmoChicken** [comment]
@noblockhit   You're not alone!  I was using an M-Audio AIR 192|6 USB audio interface, and had pretty much the exact same frustrating experience that you described.  And no fault of the AIR 192|6, which worked perfectly and as it should.  Rather, Teams simply refused to acknowledge channel 2.

As I wrote above, my solution was to purchase a USB mixer, and use it instead of my M-Audio AIR 192|6 USB audio interface.  But that's not the only solution. For example, you could purchase a fairly cheap (~ $70) analog mixer, plug the output of the mixer into input 1 (left channel) of your Yamaha UR 22mk 2, then plug your mic and guitar into the mixer and mix as desired.  Of course, you'll need to be sure that you buy a mixer that (a) can accept a guitar as an input, and (b) has phantom 48V power, if needed.  Also if needed, you'll want a mixer that has XLR output that you can plug into your audio interface.

Or you could buy a USB mixer, such as a Mackie ProFX6v3, ProFX10v3, or ProFX12v3.  :) 

@Wajeed-msft  @Subhasish-msft @Abhijit-MSFT   Many of us would like to use BOTH channels of our USB audio interfaces.  Please resolve this issue.
