### ISSUE TITLE
Can't update message

### ISSUE THREAD

**Issue by jerry-le** [MicrosoftDocs/msteams-docs#1646]
By using the REST API `PUT /v3/conversations/{conversationId}/activities/{activityId}
`, I always encounter this error when trying to update an existing message:

```json
{
    "error": {
        "code": "BotNotInConversationRoster",
        "message": "The bot is not part of the conversation roster."
    }
}
```

The request body:
```
{
	"type": "message",
	"text": "New message "
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 293d28d8-bd82-299a-05b3-4f798e485542
* Version Independent ID: 2f747d61-5ff7-be26-d55d-fdc715f4293d
* Content: [Update and delete messages sent from your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/update-and-delete-bot-messages?tabs=dotnet)
* Content Source: [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/update-and-delete-bot-messages.md)
* Product: **msteams**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **anclear**

**Comment by jerry-le** [comment]
@clearab please help

**Comment by Gousia-MSFT** [comment]
@jerry-le Could you please share some piece of code you are trying? Also, here is a similar [issue](https://stackoverflow.com/questions/61614466/receive-forbidden-error-when-try-to-update-or-delete-bot-activity-in-ms-teams) reported few days back. Could you please check if your issue is similar to this?

**Comment by jerry-le** [comment]
Thanks, Gousia.

By following the issue you mentioned above, it's turned out I got the same mistake. I should get the activity id from the response instead of the id receiving when the user makes an action (a button on an adaptive card in my case)

But it's leading to another issue. When I send an activity with text only, the response has `id` field, but when the activity includes an attachment (which is the adaptive card in my case) the response has `id` but with empty string value.

**Comment by nikosalexakis** [comment]
Hi,

I just want fo add here that I have the same issue
even if no text is set and only attachments (adaptive card or hero card).
If my reply contains only 1 attachment, I get back an activity `id` otherwise if more than 1 attachments (cards) are present in the reply, then the I get back an empty object.
example message:

```
{
  "text": "",
  "summary": "I found a relevant article.",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.0",
        "body": [
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "text": "I found a relevant article.",
                "wrap": true,
                "isSubtle": false
              },
              {
                "type": "TextBlock",
                "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                "wrap": true,
                "isSubtle": false
              }
            ]
          }
        ],
        "actions": []
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "",
        "subtitle": "",
        "text": "",
        "images": [],
        "buttons": [
          {
            "title": "Yes",
            "value": "Yes",
            "type": "messageBack",
            "displayText": "You clicked \"Yes\""
          },
          {
            "title": "No",
            "value": "No",
            "type": "messageBack",
            "displayText": "You clicked \"No\""
          },
          {
            "title": "Test",
            "value": "Test",
            "type": "messageBack",
            "displayText": "You clicked \"Test\""
          }
        ]
      }
    }
  ]
}

**Comment by clearab** [comment]
@aosolis please correct me if I'm wrong - If you send more than one attachment the Teams backend will split your message into more than one activity, which is why you end up with no Id. The best way to handle this is to send a separate message for each attachment.

The same thing is happening when you send both text and an attachment - it is getting split into two messages. You unfortunately need to send them separately.

**Comment by aosolis** [comment]
@clearab is correct, the service “splits” the list into individual messages.

If your scenario is to update the card in response to a click on a button on the card, then another option is to use the replyToId in the message. That will contain the ID of the activity with the card, so you can use it to update.

If you need to update the message proactively, or if you’re updating a different message, then the only option is to send the list in separate messages :(

**Comment by nikosalexakis** [comment]
@aosolis @clearab thanks for the reply. 
I can understand that the message is split into multiple activities and why I don't get back a single activityId.

IMO though this is not the expected behavior.
Since I am only sending **1 message**, I should get **1 activityId** (even if multiple attachments are present, which is valid btw.). MS Teams could group them into 1 activity and let the rendering do the splitting.

Use case:
I need to send out 1 message (Msg_1) and replace part of the content when a button is pressed.
The message (Msg_1) consists of 2 attachments: 
- Attachm_1 (Text content)
- Attachm_2 (Buttons-actions)

On a button click on Attachm_2 I need to update both --> Text content in Attachm_1 and buttons in Attachm_2

Now, even if I send the attachments one by one and store them locally:
 - if a button is clicked on Attachm_2 I will get the replyToId of just Attachm_2
 - I don't get any info about the activityId of Attachm_1, which I also need to update
 - This means, I need to store and manage locally mappings/groups and order of appearance for each activityId sent.
As you understand this makes it much more complex than it could be. 

I would propose 2 enhancements:
1. MS Teams returns a single activityId for a single message(even with multiple attachments)
2. MS Teams sends on a button-click (action) the payload, replyToId together with the original message-JSON. This way we don't need to store locally messages that have been sent to users. Our code adjusts the message-JSON and uses updateActivity with the replyToId to update the message. (Note: this is also what Slack does for interactive messages and it is much easier to handle them)

Thanks

**Comment by Gousia-MSFT** [comment]
@nikosalexakis Thanks for sharing your suggestions here.
