### ISSUE TITLE
Microsoft Team's incoming webhook not working if used in Google Cloud Monitoring service

### ISSUE THREAD

**Issue by edbergavera** [MicrosoftDocs/msteams-docs#1718]
We are having issues sending webhook to MT channel from Google Cloud Monitoring service. The webhook URL works when tested locally on my laptop. So this is not an issue with the webhook either. According to Google Cloud support, it's possible that Microsoft blocked the request from Google Cloud Monitoring that contains a header `User-Agent: Google Alerts` that might not be recognized or not allowed.

**Comment by Nikitha-MSFT** [comment]
Unable to repro the issue with UA set to “Google Alerts”.
Also, Incoming Webhooks do not have any filtering on User-Agent for Webhook messaging on Connectors side and so that should not be an issue.
We would need the following details from the user to troubleshoot this further:
Failure response content from the connector along with response headers when sending message to the below webhook URL, or Network capture of the failed request made to the webhook URL.
Please note that Incoming Webhooks currently support only the message card format:

[https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference)

**Comment by edbergavera** [comment]
@Nikitha-MSFT as per MT dev Pradeep Anantharaman's response, this might not be possible at the moment:

> I see that the webhook URL is set up to receive directly from this external app, and the payload schema from them would not match message card format and this is why it can fail.
> 
> The payload schema needs to be of message card format: https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference
> 
> So, for solving this, you can set up an intermediate service (webhook API hosted at your end) that transforms the payload from this external app “Google Cloud monitoring” into message card format and then send this payload to Incoming Webhook.
> 
> Hope this helps!
