### ISSUE TITLE
microsoft teams app bot tab and notification

### ISSUE THREAD

**Issue by MarwaAbuEssa** [MicrosoftDocs/msteams-docs#1735]
Hi ,

I'm using your nodejs botbuilder v4 to create a notification only bot and add it to microsoft teams app . when an event occurs at our Backend API it sends to /api/notify using ngrok  which will send a proactive message to bot at our app in microsoft teams app and it works ! .

when a member added it starts a conversation and the notification continue sending successfully . now when i restart my ngrok (which runs my bot app), the notification is stopping !! as i found out the code using( await adapter.continueConversation).and i found that to continue conversation  to bot , user must send a message to bot to start a conversation . my bot is going to be a notification only bot , so my question now is how to send a proactive message to a notification only bot to a certain user (by creating a conversation if not exists ) and not stop even if i restarted my bot app ngrok.

Regards ,
Marwa

**Comment by Wajeed-msft** [comment]
@MarwaAbuEssa -  The [sample code](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/16.proactive-messages/Bots/ProactiveBot.cs#L19) saves conversation reference in memory, you should be saving it to permanent storage may be some database. So that even after restarting ngrok you could send proactive message.
