### ISSUE TITLE
Teams incoming webhook returning status 200 on error

### ISSUE THREAD

**Issue by jamyspex** [MicrosoftDocs/msteams-docs#1810]
When posting an action card into Teams that is over the maximum allowed size, the response used to have the status code 413. Since approximately 22/06/2020 the response has change to have a 200 OK status code with a message saying:

`Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 413 with ContextId tcid=622824298674363899,server=DB5PEPF00003FC8,cv=AszFFaeXdEGdFrJhai0eUw.1.0,MS-CV=AszFFaeXdEGdFrJhai0eUw.1.0..`

Can this response be reverted to have a 413 error code as it is much easier to detect. 

Cheers, James.

**Comment by Nikitha-MSFT** [comment]
Teams returns 413 for large messages and the behavior at Connector's end has always been to wrap it with 200 OK response. 
The reason is that many 1st party connectors like Trello, Asana, etc treat any non successful status code as connector issue and removes configuration, and stops sending further events. So, they return 200 with error in the response content/body.

**Comment by jamyspex** [comment]
OK thanks for the info.
