### ISSUE TITLE
If admin uses app setup policy for org, does my bot get notified for all user's installations individually? 

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1926]
As an admin, if I set an app to "install for all users" when does the "onboarding" happen for each user? Is it all at once or when they sign in? And does my running app get notifications for **every** single install that happens for every user? (I need to make sure that every individual user gets the proper onboarding/installation message.)

I'm having difficulty testing this out because after installation ONCE and proceeding **un**installation, any time I test installation my bot isn't being notified about the second installation attempt.

**Comment by Nikitha-MSFT** [comment]
This is by design. For a 1:1 conversation between the bot and a user (personal scope) the event is only sent the very first time the bot is installed. Technically, it is sent when the conversation is created between the bot and the user. If the user uninstalls the bot, this conversation is not deleted, so if the user then re-installs the bot the event is not sent.
For Group Chats and Channels the event will be sent each time the bot is installed. This is because each time the bot is uninstalled from this context, it is actually completely removed from the conversation, so an uninstall triggers the event.

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any other queries here
