### ISSUE TITLE
What if conflict with AAD settings

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/msteams-docs#2001]
Hi,

since this was announced for roll out in the message center (ID: MC218561).
I was wondering what happens if the AAD settings for consent is in conflict with the settings in MS teams. Who rules over the other?
might there be a risk that this is disabled in AAD but allowed in MS teams?

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Gousia-MSFT** [comment]
@xNiklasJern All the RSC permissions defined for your app will be taken from the manifest file only. Azure AD portal cannot be used for RSC permissions.

**Comment by xNiklasJern** [comment]
@Gousia-MSFT yes, but what will prevail of the option in aad is set to that user can't approve application to have access to data in the tenant, but teams has the configuration it can. what will prevail?

**Comment by Wajeed-msft** [comment]
@xNiklasJern - There are two different set of permissions we are taking about here:
1. **AAD Permissions:** These can be only configured in Azure AD and needs go through either [Delegated permission](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2Fbeta&view=graph-rest-beta) or [Application permission](https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-beta) flow. To provide user login experience in Microsoft Teams, you need to implement this via [Teams authentication flow](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab). 
2. **RSC Permissions**: This can only be configured in App Manifest (Not available in Graph permission listed in Azure App). To get these permissions, you need to specify all of these in App Manifest. Owner of Team can always consent to these permissions provided that [RSC is enabled in your Tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#configure-group-owner-consent-settings-in-the-azure-ad-portal). 

In case of an App which is using both the permissions, installation of App Manifest by team owner grants app permissions listed down in App Manifest (RSC Permissions). In order to get additional permissions (AAD Permissions), you need to show Sign In button and get it approved for additional permissions. Note that not all permissions are supported in RSC, please take a look at the [permissions list](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#resource-specific-permissions).

**Comment by Gousia-MSFT** [comment]
Please re-open if you have any other queries here.
