### ISSUE TITLE
Too easy to create new chat in Teams view instead of replying to existing chat.

### ISSUE THREAD

**Issue by griztown** [MicrosoftDocs/msteams-docs#2018]
If you want to reply to an existing chat on the Teams view, you usually end up creating a new thread instead of replying. You have to click the "reply" link to open a dialog to enter a reply. But right below it is a dialog to enter a new message. Which is where I typically think to go to reply. I think it would make more sense to have a dialog for each thread and then an icon or link to start a new thread.

**Comment by Trinetra-MSFT** [comment]
@griztown , Could you please clarify which conversation type you are talking about? is it 1:1, Group Chat or Channel Conversation? is it about the channel reply conversation?

**Comment by griztown** [comment]
I think Channel? It is the third one down on the left. first is activity, then chat, then "Teams". So perhaps that is a channel?

**Comment by Trinetra-MSFT** [comment]
@griztown , This is by design for channel conversation. Channel reply showed up below the posted messages in channel and having conversation over that message. New message/conversation area is for opening a new conversation in channel not on existing thread.
Please see this screenshot
![image](https://user-images.githubusercontent.com/50989436/91811593-5f13ee00-ec4d-11ea-8144-1178b22b6937.png)
