### ISSUE TITLE
Status not changing after leaving a call (sometimes)

### ISSUE THREAD

**Issue by Niru2169** [MicrosoftDocs/msteams-docs#2025]
I have noticed that my schoolmates' statuses and my status remains as "In a call" or "In a meeting" even after leaving the call but that doesn't happen everytime.
This leads to misconceptions many times.
Look at the top right corner
This is what happens and I am not in a call at all.
Please fix it
![image](https://user-images.githubusercontent.com/66010447/91417620-b4778600-e86e-11ea-9e3a-333be0481376.png)

Thanks

**Comment by Trinetra-MSFT** [comment]
@Niru2169 , We have forwarded your query to right channel. Will get back to you in sometime. Thanks for your patience

**Comment by Trinetra-MSFT** [comment]
@Niru2169 , "In a meeting" probably still holds as the person left the call, because effectively the meeting is likely still going on from a calendar perspective. That's why the person likely transitioned from "In a call" to "In a meeting". When the meeting ends in calendar that's when we expect the status to change to something else (Available busy etc. based on user context). Could you please provide the logs for further investigation?
