### ISSUE TITLE
Load a list of templates in Search based message extension.

### ISSUE THREAD

**Issue by LuciferDoCode** [MicrosoftDocs/msteams-docs#2227]
I want to load a list of templates `['template a', ' template b', 'template c']` inside a search based message extension and I want that template to be loaded as a plain text inside the compose message box.

But Before I load that template in the compose message box, I want to do some quick action.
Let's say I have selected `template a` from the list. Upon the selection of the template, I should receive a selectItem event (Just like it's mentioned in the [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/search-extensions) but it's not working). 
After I receive the event, I would be able to modify or change the template on my service & then I will return `template a` to the Message Extension.
The returned `template a` should be loaded into the compose box as a plain text so that the end user will be able to modify the same text and able to send it to teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06016378-5b30-cc4e-e53a-a9c46a2a3a13
* Version Independent ID: d013f99a-0ee5-67d3-ee79-67bc1a0b4557
* Content: [Define messaging extension search commands - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/define-search-command)
* Content Source: [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Wajeed-msft** [comment]
@LuciferDoCode  - Apologies we missed this question. Adding answer for community members with same query.

1. In order to get event when user select any item from result, you need to first add Tap action and handle `OnTeamsMessagingExtensionSelectItemAsync`. 
You can find complete code here: [Teams Messaging Extensions Search](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search/Bots/TeamsMessagingExtensionsSearchBot.cs)

```
            var previewCard = new ThumbnailCard
            {
                Title = "First",
                Tap = new CardAction { Type = "invoke", Value = "1" }
            };
```

```
        protected override Task<MessagingExtensionResponse> OnTeamsMessagingExtensionSelectItemAsync(ITurnContext<IInvokeActivity> turnContext, JObject query, CancellationToken cancellationToken)
        {
            // Handle the select item event
        }
```

2. As a response to select item we can only send card attachments like Hero card, Adaptive card. Sending plain text is not supported. You can find more details in [Respond to user requests](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=dotnet#respond-to-user-requests) documentation. 

Marking this issue as close for now, but feel free to re-open if you are still facing any issues.
