### ISSUE TITLE
Cannot load Developer Preview manifest schema

### ISSUE THREAD

**Issue by liuwinshen** [MicrosoftDocs/msteams-docs#2265]
When in Developer Preview mode, with custom app uploading turned on for my tenant, I get the following error message:

> Please fix these validation errors and try importing again.
> /manifestVersion must be equal to one of these defined values "1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, Localization"

However, the [Developer Preview page](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview) explicitly says to use "devPreview" as the manifestVersion. May you please provide guidance as to how to import the Developer Preview Manifest schema into App Studio in Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b449c9ba-a94c-4012-4721-cee5f87eeb8a
* Version Independent ID: b2536bbc-eb27-547d-d7f5-bab3ded3bedf
* Content: [Developer Preview Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview)
* Content Source: [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/schema/manifest-schema-dev-preview.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Trinetra-MSFT** [comment]
@liuwinshen , App Studio is using the manifest version 1.7 as of now when we create new app manifest through App studio, However i was able to repro your scenario when I tried to upload an existing package having devPreview as manifestVersion it throws me the same error
![image](https://user-images.githubusercontent.com/50989436/97957460-3f29b380-1dd1-11eb-9cac-4e3614181391.png)

I will suggest you try to sideload the app with manifest version devPreview in teams rather than installing it through App Studio which will work for sure
![image](https://user-images.githubusercontent.com/50989436/97957544-7009e880-1dd1-11eb-872c-adb1de2f7066.png)

**Comment by liuwinshen** [comment]
Thanks @Trinetra-MSFT! Yes, I was updating the manifest of an existing app to use the developer preview schema for Teams Meetings. I will use the custom app option instead. Thank you for your help!
