### ISSUE TITLE
Hyperlink in DeepLink calendar appointment

### ISSUE THREAD

**Issue by vitaliishandra** [MicrosoftDocs/msteams-docs#2335]
I am creating the calendar appointment deep link.
Is i possible to insert the hyperlink in 'content' (body) of DeepLink calendar appointment body?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment]
We are Checking it internally, We will get back to if need need more information.

**Comment by Nikitha-MSFT** [comment]
Currently You cannot pass the hyperlink to the content of the meeting using deeplink. Currently deeplink support sending the plain text. This is by design. Could you please raise a user voice [here](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform)?
