### ISSUE TITLE
Incorrect sorting in case of numeric characters in filename

### ISSUE THREAD

**Issue by SaurabhS78** [MicrosoftDocs/msteams-docs#2398]
- Seems like sorting on the filename is doing a character-wise sort that works perfectly for alphabetical characters but fails if the filename consist of numerical characters too.
- For e.g. File 1, File 2 and file 10 are sorted as `File 1` , `File 10` and `File 2`
- This bug is present on both - the desktop as well as the web app
![image](https://user-images.githubusercontent.com/60143770/100470280-f3330b80-30fd-11eb-9d32-321bbdcb4824.png)

**Comment by Mallipriya-MSFT** [comment]
Hi @SaurabhS78,

The sorting is character by character, so it compares "9" to "1", not "10", because the nine and the one are in the same position within the name. If you put a zero in front of the nine, such as "09" it will sort how you want because the zero will be compared to the one.
For each additional digit in your number length, you would need to pad with another zero. 

Here is an example of how the sorting works:

Tutorial - 01.Doc
Tutorial - 05.Doc
Tutorial - 1.Doc
Tutorial - 10.Doc
Tutorial - 2.Doc
Tutorial - 21.Doc
Tutorial - 22.Doc
Tutorial - 3.Doc
Tutorial - 5.Doc
