### ISSUE TITLE
Adaptive card image extend issue

### ISSUE THREAD

**Issue by shangec** [MicrosoftDocs/msteams-docs#2838]
Thank you, thank you, thank you! I am so happy we now have this small, but rather useful/practical feature in Teams. Very much appreciated @siduppal for your help with this and for providing updates over time. 

I can confirm that it works as expected on our side. Thanks again.

Fingers now crossed for first-class citizen treatment of private channels (ie support for bots, etc).

_Originally posted by @stpeteparadox in https://github.com/MicrosoftDocs/msteams-docs/issues/388#issuecomment-676856104_

Hi @stpeteparadox,

I'm encounter the same issue, can you reply me how did you solved?

Thank you so much

**Comment by stpeteparadox** [comment]
> Hi @stpeteparadox,
> 
> I'm encounter the same issue, can you reply me how did you solved?
> 
> Thank you so much

Hi @shangec, 

Please would you clarify what is the same issue you are referring to? If you mean the issue we mentioned at the very end of #388, then all I can say is that we didn't do anything -- the issue resolved itself at some point. 

We still need to keep users' Teams apps in Developer-mode in order to use this image expandability feature though. Hopefully this will go mainstream soon - it is a rather basis and expected feature! Thanks again to @siduppal

**Comment by shangec** [comment]
Hi @stpeteparadox ,

![image](https://user-images.githubusercontent.com/52879952/109765290-9a5c9d00-7c2f-11eb-9204-233c22cfd0ff.png)

I wonder if this property works for you?

Now, in my case, if a content contains an image, I had to separete the image from the content and used the follow code then the image could be extended in the Teams chatbot,
`Attachment attachment = new Attachment()
{
  ContentType = "image/png",
  ContentUrl = "https://via.placeholder.com/1000"
};`

**Comment by stpeteparadox** [comment]
Hi @shangec 

Yes, sending an image as an attachment I believe has always had the image expandability feature on it (it that case you can click anywhere to expand it -- this is similar behavior to a human user uploading an image in Teams GUI).

But for adaptive cards, if you want the image inside the body, then that is where the expandability feature was missing for a long time, until the new allowExpand sub-property.

We have not had any problems with it. But do make sure that you put your Microsoft Teams application into Developer mode, otherwise it won't work.

We send post our adaptive card using an Azure Logic App. Here is sample card json that works for us:

`{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"body": [
		{
			"items": [
				{
					"size": "Medium",
					"text": "{text here}",
					"type": "TextBlock",
					"weight": "Bolder",
					"wrap": true
				},
				{
					"isSubtle": true,
					"size": "Small",
					"spacing": "Small",
					"text": "{text here}",
					"type": "TextBlock",
					"wrap": true
				}
			],
			"type": "Container"
		},
		{
			"items": [
				{
					"horizontalAlignment": "Center",
					"msTeams": {
						"allowExpand": true
					},
					"separator": true,
					"type": "Image",
					"url": "{url here}"
				}
			],
			"type": "Container"
		}
	],
	"type": "AdaptiveCard",
	"version": "1.2"
}`

**Comment by shangec** [comment]
Hi @stpeteparadox ,

Thank you very much, it work for me.

But this means, we should tell all users let they change their Teams to the Developer mode?

**Comment by stpeteparadox** [comment]
Hi @shangec 

Yup. Everyone viewing the adaptive card needs to have dev mode in Teams turned on in order to get the expand feature.

The dev preview of this feature was 'officially' announced it seems on 2021-01-27: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features

Hi @siduppal, do you know when this feature will move to production?

**Comment by shangec** [comment]
Hi @stpeteparadox 

Ok, I know, thank you very much again.

Hope this feature will be put into production soon. @siduppal

**Comment by shangec** [comment]
![image](https://user-images.githubusercontent.com/52879952/109927257-e0ccfd00-7cfe-11eb-9d52-ec84426d4d3b.png)

@stpeteparadox 
Do you know how to implement this function in Teams chatbot?

**Comment by Nikitha-MSFT** [comment]
@shangec - You can add bot commands in the manifest to show suggestions to user when user opens a chat bot. Please check this [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu?tabs=dotnet) for more info.

**Comment by shangec** [comment]
@Nikitha-MSFT Got it, thank you so much
