### ISSUE TITLE
Tablet with keyboard cannot input when tap chat input textbox

### ISSUE THREAD

**Issue by danhnh** [MicrosoftDocs/msteams-docs#2881]
I'm using galaxy tab s7+ with book cover, tap into chat message input, i cannot typing and onscreen keyboard show with no characters.

**Comment by Mamatha-MSFT** [comment]
@danhnh According to your description, your issue is more related to Teams product, which we do not support. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams. Thanks for your understanding and patience!
