### ISSUE TITLE
Live stream window only accessible in full screen

### ISSUE THREAD

**Issue by krysalead** [MicrosoftDocs/msteams-docs#2892]
Hi,

Platform: Mac Mojave 10.14.6
Microsoft Teams Version 1.3.00.33671. updated on 3/11/21.
When I am clicking on a notification message during a live streaming session I am not able anymore to go back to the live session in standard mode. I can only go in full screen. Clicking on the PIP at the bottom right is not doing anything and only clicking on the full-screen button allow me to go back to the live session.
If you need more info let me know

Regards

**Comment by Mamatha-MSFT** [comment]
Hi @krysalead According to your description, your issue is more related to Teams product, which we do not support. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams. Thanks for your understanding and patience!
