### ISSUE TITLE
No Teams camera filters for Document, Whiteboard, etc

### ISSUE THREAD

**Issue by Andrew-SSFM** [MicrosoftDocs/msteams-docs#303]
When taking a picture from within the Teams Android App, the camera used is the default application on my LG G2 and does not provide the typical filters/modes.  In the Outlook app I am given options for Document and Whiteboard.  In the OneNote app I am given options for Document, Whiteboard, and Business Card.

I have tried uninstalling/reinstalling as well as manually removing/adding phone permissions with no luck.

I am submitting this issue based on what I saw of the Teams camera function at Ignite 2018.  It's possible that these features are still rolling out and not yet in GA (but I couldn't find anything for it in the roadmap)  Please advise if this is expected behavior at this time or in fact a bug.

Thanks!

Andrew

**Comment by billbliss** [comment]
This is not the place for such questions -- this is the place to ask questions about the developer documentation - but I checked for you anyway.

Office Lens integration for Android hasn't yet been released but it should appear in the next few weeks. It's already in iOS - not sure what was demo'ed at Ignite, but since that's further along perhaps that's what you saw.
