### ISSUE TITLE
Deep linking mobile doesn't work

### ISSUE THREAD

**Issue by xanderfehsenfeld** [MicrosoftDocs/msteams-docs#3223]
Deep links don't work in a mobile teams.

We're using deep links to transfer the focus to another static tab when the user clicks a `react-router` link. On desktop and teams for web the links work. However on mobile, a message appears "link not supported. you cannot open this link on the mobile app. Please open it on a desktop or web app." 

I'm aware the part of the part of the docs:
>Currently, shareDeepLink does not work on mobile platforms.

But we aren't using that part of the api. Instead we're using `microsoftTeams.executeDeepLink`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Mamatha-MSFT** [comment]
Hi @xanderfehsenfeld - Are you following this sample deeplink `https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>`. This error will occurs when you give incorrect entityId or appId. Please make sure to add correct values.

**Comment by xanderfehsenfeld** [comment]
@Mamatha-MSFT Yes, I am following that pattern, or more specifically 
`https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>`
I assume I'm using the right pattern because it works on the Teams desktop app as well as the "Teams for web" site. Is there a discrepancy between mobile and desktop? If so, what is it?

**Comment by Mamatha-MSFT** [comment]
Hi @xanderfehsenfeld  Could you please try to uninstall the existing app and create a new app.

**Comment by Mamatha-MSFT** [comment]
@xanderfehsenfeld Please let us know if your issue has been resolved.

**Comment by Mamatha-MSFT** [comment]
Hi @xanderfehsenfeld  is your issue got resolved?

**Comment by Krukovich** [comment]
I need your help, I am developing a bot for ms teams and in my scenario the user must be redirected from chat to tab, for this I use a deep link here is an example link

`https://teams.microsoft.com/l/entity/${process.env.APPLICATION_ID}/${process.env.TAB_ID}`

and it works great everywhere in the browser in the desktop version and in window and in ubuntu and even on Android, but as it turned out, it does not work on IOS, and specifically in the ms teams application for IOS

![image](https://user-images.githubusercontent.com/44588100/118238909-d1f28b80-b4a1-11eb-9ceb-a8f2a4cf8769.png)

however in the app on IOS I get the following.

Any hints and tips any advice that can help me solve this problem

UPDATE: a small addition today I put a desktop application on a macbook and there was no such problem. So the problem occurs only in the mobile application

**Comment by Mamatha-MSFT** [comment]
@xanderfehsenfeld Could you please add webUrl in your deeplink and try. Let me know if the issue still persists.

**Comment by Krukovich** [comment]
@xanderfehsenfeld Thanks for the quick response, I tried your suggestion and got the following behavior after clicking on the button, the browser was opened, then there I was redirected back to the application, after which this error was reproduced again

this is an example link

https://teams.microsoft.com/l/entity/${process.env.APPLICATION_ID}/${process.env.TAB_ID}?webUrl=https://teams.microsoft.com/l/entity/${process.env.APPLICATION_ID}/${process.env.TAB_ID}`

**Comment by Mamatha-MSFT** [comment]
@xanderfehsenfeld - the weburl should be static tab content url which you gave in manifest like https://tasklist.example.com/123
Example:  `https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123`

**Comment by Krukovich** [comment]
@Mamatha-MSFT 
Yes I have a static tab in my manifest here is an example 
```js
  "staticTabs": [
    {
      "entityId": "91dd4c30-9744-42e8-941a-c129b167f1e9",
      "name": "PandaDoc",
      "contentUrl": "https://{{HOSTNAME}}/pdTab/?name={loginHint}&tenant={tid}&theme={theme}",
      "scopes": [
        "personal"
      ]
    }
  ],
  ```
it turns out that my link should look like this

`https://teams.microsoft.com/l/entity/${process.env.APPLICATION_ID}/${process.env.PANDADOC_TAB_ID}?webUrl=https://${process.env.HOSTNAME}/pdTab/?name=${name}&tenant=${tenantId}`

and replacing the path I get the following behavior opens a new window in the browser and gets me out of the Teams app, is this the correct behavior?

**Comment by Mamatha-MSFT** [comment]
@Krukovich - We have a backlog bug item for this and will inform you if it gets resolved.

**Comment by Mamatha-MSFT** [comment]
@Krukovich - Could you please share the complete deeplink url your using and manifest.

**Comment by Krukovich** [comment]
@Mamatha-MSFT yes of course I can send it to you by mail

**Comment by Mamatha-MSFT** [comment]
@Krukovich Please write a mail to microsoftteamsdev@microsoft.com

**Comment by Krukovich** [comment]
@Mamatha-MSFT I sent you our manifest and a small example of code how we use deep link by e-mail

**Comment by marcinburak** [comment]
Same here. Deep links work in MS Teams web client, Windows desktop, Android, but no luck using iOS mobile.

**Comment by Mamatha-MSFT** [comment]
@Renevdo @marcinburak  we have created a bug for this issue and concerned team is working on it.

**Comment by Mamatha-MSFT** [comment]
@Krukovich @Renevdo There was a fix done for this issue in latest store app. Please check.

**Comment by Renevdo** [comment]
I can confirm that it's fixed on IOS in Teams!
