### ISSUE TITLE
Explanation of Deep Links to File in Channel could be more clear

### ISSUE THREAD

**Issue by mattpanico** [MicrosoftDocs/msteams-docs#3923]
There are several points in the "Generate deep links to file in channel" section that are unclear and could use more explanation:
- `objectUrl`: There's no guidance here on where to obtain this URL. Is it a URL the developer can get from a Graph API?
- `baseUrl`: Similarly, it's not clear what we should put in this field. The section includes two examples which don't agree with each other: `https://microsoft.sharepoint.com/teams/` and `https://microsoft.sharepoint.com/teams/ActionPlatform`
- `serviceName`: It's not clear what we're expected to include here. Should it just always be 'teams'?
- `threadId` and `groupId`: in Teams terms, it appears that these should be the IDs of the channel and team, in that order. However, the description for `threadId` says that it is the Team ID, which does not appear to be true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generate-deep-links-to-file-in-channel)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/deep-links.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. We will update the status to you soon.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Hello @mattpanico,
ObjectUrl - https://{tenantName}.sharepoint.com/sites/{TeamName}/Shared Documents/{ChannelName}/FileName.ext 

BaseUrl - https://{tenantName}.sharepoint.com/sites/{TeamName} 

ServiceName = teams 

 If you see the URL(while in channel), you can find both threadId as well as groupId. That's why its like that only.


You can also get all these value by navigating to Teams -> Team -> Channel -> Files
![image](https://user-images.githubusercontent.com/64194049/129190288-05f0cd3b-efb6-4e4c-ac94-0c338c5a7d9a.png)
Hover over any file click on 3 dots (...) and select _Copy Link_
![image](https://user-images.githubusercontent.com/64194049/129190513-25005ed4-a20c-4cac-8a73-9b1a1fdb411a.png)
Make sure that you are copying link while under this tab:
![image](https://user-images.githubusercontent.com/64194049/129190811-e02b4bc7-563a-47b6-91d1-3fccc6f0daa0.png)
