### ISSUE TITLE
What kind of risk factor the incoming webhooks are causing to us?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/msteams-docs#4523]
Hi there,
I have tested these web hooks, and one big surprise was that I was able to send anonymously a message into our Teams. This looks like enabling email, then people can send emails to Teams.

But compared to email there seems to be few differences:
- Emails are scanned, web hooks seems to be not scanned
- We could limit if we are not allowing externals to send emails into our Teams, with web hooks I have not seen such option.
- By the PowerShell we are able to list Channels enabled for email, but so far I have not found any possibilities to list channels which have web hooks

Could you please share on this page what security controls we could add to incoming web hooks?

rgs
Petri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment]
We are checking internally. I will get back to you soon.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
The new design includes tenant-specific domain for webhook so that tenant can inspect SNI (Server Name Indication) during TLS negotiation to prevent connection to other tenant’s webhook within their own perimeter. 

The endpoint is updated to -
https://[tenant_name].webhook.office.com/webhook/[external_object_id]@[tenant_id]/[connector_type]/[instance_id]/[owner_object_id]

Webhook service validates [tenant_name] and [tenant_id] are pointing to the same tenant.

Please refer to below on searching audit logs, and is available for Connectors/Incoming Webhooks as well.
[Audit log search - Security & Compliance (office.com)](https://protection.office.com/unifiedauditlog)
[Search the audit log for events in Microsoft Teams - Microsoft Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events#teams-activities)

**Comment by HunaidHanfee-MSFT** [comment]
Please re-open if you have any query, we are closing it as of now.
