### ISSUE TITLE
composeExtensions[0].scopes isn't working though it is shown as a required property in the documentation

### ISSUE THREAD

**Issue by kartikluke** [MicrosoftDocs/msteams-docs#565]
Without setting the scope to just one of the scopes the message action button shows up twice.

<img width="616" alt="Screenshot 2019-04-15 at 12 43 46" src="https://user-images.githubusercontent.com/3857139/56113669-230abb00-5f7c-11e9-93aa-b0da426bc575.png">

```
Error: An error occurred while parsing the manifest.json file; Property 'scopes' has not been defined and the schema does not allow additional properties. Path 'composeExtensions[0].scopes', line 49, position 21.
```

**Comment by Wajeed-msft** [comment]
@kartikluke - Message extension does not support scopes. That's the reason you are getting error while parsing. 
![image](https://user-images.githubusercontent.com/31851992/56116219-eabaab00-5f82-11e9-8bfa-8056ec96f74e.png)

**For multiple entries issue:** 
This is happening because every time you sideload an app, different id is assigned to it. So, you have different app in personal scope and different in team scope.
 
Try any of these to get rid of multiple entries:
1. Uninstall your personal scope app. Now, it will show only one entry from the app installed in the team scope.
2. Uninstall both in team and personal scope. Now install only in Team scope. Click on the app name link and then chat icon. This will take you to your personal app.
![image](https://user-images.githubusercontent.com/31851992/56116352-3c633580-5f83-11e9-902e-19d671e3a2cf.png)
Now click on Add button which pops up at the top.
![image](https://user-images.githubusercontent.com/31851992/56116423-60267b80-5f83-11e9-9b9c-d066f7234919.png)
3. Install your app in [Private App store](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams).

Please let us know if you face any other issue.
