### ISSUE TITLE
MS Graph ASP.NET Core / Teams examples

### ISSUE THREAD

**Issue by ccit-spence** [MicrosoftDocs/msteams-docs#575]
Are their any examples for ASP.NET Core using the Graph Client SDK?

Docs for the SDK and Teams would be helpful if no samples exist.

**Comment by billbliss** [comment]
I don't believe there are, but I'll check. One of the frequent discussions we have among MS Graph stakeholders internally is that the SDK doesn't get used as often as many think it should be - in no small part because there's no SDK for beta APIs.

It's a royal pain to serialize and deserialize JSON in C# compared to Node.js (and therefore a pain to use REST APIs) because you need all those wrapper classes, so I agree they would be helpful!

**Comment by Wajeed-msft** [comment]
Microsoft Graph documentation team started putting SDK sample code in the respective pages. Please take a look at [Create Group](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=cs#sdk-sample-code) documentation. I have raised new issue on [Create New Teams](https://github.com/microsoftgraph/microsoft-graph-docs/issues/4974) doc page for sample code.
