### ISSUE TITLE
Default option on developer mode

### ISSUE THREAD

**Issue by amajchrzak** [MicrosoftDocs/msteams-docs#5858]
Hi, 
I really don't want to use developer view in Teams as the emoticons in it are horrible. Unfortunately with each Teams restart the app returns to this mode. I really miss the info on this page how to cope with my issue and this default mode setting... I really want to switch it off permanently.
Thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008da4e2-979e-c396-db28-4acf57deb530
* Version Independent ID: f1413f77-5eb3-e1fd-9235-d322d6e4eb6c
* Content: [Developer Preview - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro)
* Content Source: [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/dev-preview/developer-preview-intro.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@amajchrzak - Is your Teams update policy is set to be Follow Office Preview?
Please check by following steps.
1.Sign in to the [Microsoft Teams admin center](https://admin.teams.microsoft.com/).
2.Select Teams > Teams Update policies.
3.Select an existing policy to open Update policy.
4.Select the setting for Show preview features.


![image](https://user-images.githubusercontent.com/92150070/167084296-931067f4-e239-4ab3-96e7-99db0177a82f.png)


If its Follow Office Preview then you have to set as Not Enabled because its a Known issue for Follow Office Preview
![image](https://user-images.githubusercontent.com/92150070/167084344-3853da81-0401-469a-8964-60fec33b1be9.png)


Ref doc: https://docs.microsoft.com/en-us/MicrosoftTeams/public-preview-doc-updates#known-issues
