### ISSUE TITLE
How to Fetch Org-Wide Roster?

### ISSUE THREAD

**Issue by isaacdchan** [MicrosoftDocs/msteams-docs#621]
I need the MS Teams unique_id and tenant_id of all users in my org. 

This document details how to fetch the unique_id and user tenant_id of all users in a team
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#fetching-the-team-roster

This document details how to fetch only the tenant_id of all users in an org. I'm assuming because that user may not have registered in Teams
https://www.c-sharpcorner.com/article/get-all-organization-users-from-o365-using-graph-api/

The only solution I can think of is getting the tenant_id of all users in org, then assuming they're all members of at least one team, fetching the team that user is a member of and finding the user_id that matches the tenant_id.

This seems like a terrible waste of time. Unfortunately our org is too large to create an org-wide team.

**Comment by 01** [comment]
@isaacdchan Unfortunately their is no way to get the user id for all those in an organization (many of us are waiting on a solution as well). The user id is  unique for each bot - user combination so there is no one user id to be able to use.  The only way to obtain the user id is from a direct message to bot, the single conversation update event that happens if someone installs the bot, or a user being part of a team the bot is also added to.

The only real one step solution as of now is the have a org wide team and add the bot to it.

**Comment by isaacdchan** [comment]
@01 Appreciate the insight. Will close the issue and pray for this feature in a coming update.
