### ISSUE TITLE
The provided code to open the scheduling dialog in TeamsJS v2 does not work in Teams

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/msteams-docs#6303]
In order to open the scheduling dialog in Teams, developers need to continue using the original deep-link URL based method since Teams does not yet support the `calendar` capability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#open-a-scheduling-dialog)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
@AE-MS - Should we ask the documentation team to remove the provided code for TeamsJS V2 and mention a note saying - "In order to open the scheduling dialog in Teams, developers need to continue using the original deep-link URL based method since Teams does not yet support the calendar capability"

**Comment by AE-MS** [comment]
I think that sounds right, yes.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please remove the provided [code for TeamsJS V2](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#open-a-scheduling-dialog) and mention a note saying - 

"In order to open the scheduling dialog in Teams, developers need to continue using the original deep-link URL based method since Teams does not yet support the calendar capability"
