### ISSUE TITLE
The query parameter is still called `subEntityId`

### ISSUE THREAD

**Issue by rabwill** [MicrosoftDocs/msteams-docs#6361]
In v2  `subEntityId` is now `subPageId` in the [context info](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit#updates-to-the-context-interface)  yet in the query parameter when generating a deeplink, it is still called `subEntityId`.  

We have already mentioned this is a name change [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?WT.mc_id=m365-58890-cxa&tabs=teamsjs-v1#consume-a-deep-link-from-a-tab). 

Is there a reason why the context query parameter is not renamed to subPageId?

Example:

- Link to a task item within the static (personal) tab:
 https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=https://tasklist.example.com/123/456&label=Task 456&context={"<b>subEntityId</b>": "task456"} 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45541337-ecd7-5cf6-cbe4-3f0d2f39aa79
* Version Independent ID: 6b4203f0-2844-06c9-eaa3-9cc03e6f76c0
* Content: [Create deep links - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?WT.mc_id=m365-58890-cxa&tabs=teamsjs-v2)
* Content Source: [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/deep-links.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@rabwill - We are investigating your query. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@rabwill - Please let us know if you have any other query or shall we close this issue now?

**Comment by sbtron** [comment]
@rabwill the subentityID continues to exist for backwards compatibility. While using the strongly typed APIs you can use the SubPageID parameter any url that gets generated will continue to use subEntityID. The url contruction hasn't changed just the API structure. I believe the deeplink documentation still calls out subentityID- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#generate-a-deep-link-to-your-tab 

Would love to know if you have any other input on improving the docs so its clear the URLs would remain the same. Overall, we are also trying to move away from having to construct these urls - For e.g. you can use the navigateToApp API or one of the hub specific capabilities to instead of trying to do an openlink on a constructed URL.

**Comment by ChetanSharma-msft** [comment]
Hello @rabwill - Hope you are doing well !!
Please let us know if you have any other input on improving the docs ?

If not, shall we close this issue?

**Comment by rabwill** [comment]
Thanks @sbtron and others. I was OOF but good to know we are moving away from manually constructing url. Although I have not tried it this explanation looks good. Thanks, you could close now.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue, Please feel free to reopen it, if required.
