### ISSUE TITLE
The url can use the ngrok domain name in the simulator, but does not in the card

### ISSUE THREAD

**Issue by KaratLee** [MicrosoftDocs/msteams-docs#6363]
The url can use the ngrok domain name in the simulator, but does not in the card
<img width="999" alt="image" src="https://user-images.githubusercontent.com/37133480/176837887-e02577d5-8a8b-41b8-892d-187b32cc8454.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/37133480/176837961-55a493a4-ab7a-4a9d-81c6-a0e33de84517.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/37133480/176837994-065da596-19a6-4280-b4ca-c487276656de.png">

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will update you.

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same. We will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
@KaratLee - We got the following response for the bug -

AMS does not support URLs in this format (because it indicates that this is not a public URL, as this image is being served locally through ngrok), which is why it is returning a 415. 

We recommend that images be hosted on public servers so that they can be accessible for all users.
