### ISSUE TITLE
Tab UI/content changes not reflecting for users

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#6639]
Hi Team,
If there are any content or UI changes in Tab app, changes are not reflecting for end users immediately. It may be taking 24-48 hours to reflect because of cache. It would be helpful if the same is mentioned in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7398066-a52e-7db2-c65c-9f1cf5796077
* Version Independent ID: 2dd1c170-fd52-0c27-1b9a-3664ca9f83c4
* Content: [Create a content page - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2)
* Content Source: [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-tab-pages/content-page.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - It would be better if we add a note in this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2) saying : 
"If there are any content or UI changes in Tab app, it will take nearly 24-48 hours to reflect the changes because of cache."
