### ISSUE TITLE
Start from Scratch

### ISSUE THREAD

**Issue by onceelace** [MicrosoftDocs/msteams-docs#670]
How to start from Scratch? is it necessary to start from the sample app and customize the application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment]
@onceelace Please have a look at the [Sample App](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/code-samples#get-started) and the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/concepts-overview) that would help you start building your own app. Please let us know if you need any help.

**Comment by wictorwilen** [comment]
If you want to start from scratch I can highly recommend using the Yeoman generator for Microsoft Teams. See https://aka.ms/yoteams and this simple tutorial https://github.com/OfficeDev/generator-teams/wiki/Build-Your-First-Microsoft-Teams-App

**Comment by hdg97** [comment]
@Gousia-MSFT Just letting you know, but (based on the complete sample app at https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp) much of the instructions on even running the app appears outdated. 

The README is using the wrong link to create a bot, because of the migration. Following the instructions, it says: Bot registration is here (open in a new browser tab): https://dev.botframework.com/bots, but using this will not allow us to create our own message endpoint and use ngrok, thereby rendering the instructions in the README virtually useless. Instead we are supposed to use https://dev.botframework.com/bots/new, but while we use this, it will have a warning that we should be migrating to the new bot service.

The manifest file cannot be parsed with the current Teams "upload custom app". The error I get while following the instructions is as follows.

    Error: An error occurred while parsing the manifest.json file; Property 'scopes' has not been defined and the schema does not allow additional properties. Path 'composeExtensions[0].scopes', line 150, position 15. 

I am yet to be sure as to why this is occurring, and am trying to debug this problem. I don't believe I did anything to change the manifest except for following the instructions and changing the values in <<___>>.

Not sure where it was best to post this, so let me know for next time. Thanks!
