### ISSUE TITLE
Website has missleading information

### ISSUE THREAD

**Issue by federicombo** [MicrosoftDocs/msteams-docs#6704]
[sending a task module to an anonymous user doesn't work, if  an user clicks on an adaptive card, gets a task module, and clicks to submit data- that will fail, because there's no underlying user to complete the action.submit for form submission if authentication is needed. Please correct the website information in the table for anonymous experience]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33fae5e3-2d98-381c-1b16-82c0acc6f716
* Version Independent ID: 6124f090-bdb7-c575-2614-60ec85a947b9
* Content: [Unified meetings apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop)
* Content Source: [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by sayali-MSFT** [comment]
@federicombo - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@federicombo - If an app sends an adaptive card in the chat, anonymous users can interact with the card. Such users can interact with apps in Teams meetings if the user-level permission policy enables the app. Anonymous users inherit the user-level global default permission policy.

Reference Doc-https://docs.microsoft.com/en-us/microsoftteams/non-standard-users#anonymous-users

**Comment by sayali-MSFT** [comment]
@federicombo -Did you get chance to check?

**Comment by federicombo** [comment]
Hello

You are right that the anonymous user can interact with an adaptive card.
What is wrong in the website is that you mention they can also interact
using Task Modules but that is the part that DOESNT WORK and you should
worrect it on the website.  Users can view task module content when they
click on an adaptive card button but sending a task module to an anonymous
user doesn't work. If  an user clicks on an adaptive card, gets a task
module, and clicks to submit data- that will fail because there's no
underlying user to complete the action.submit for form submission if
authentication is needed.

I hope this clarifies, you correct  in that website the Task Modules works
for external anonymous users. It only works for internal users of guest
added in AAD.
Thanks
---------------------------------------
Federico Moreno Vásquez
***@***.***

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us for the update to document?
Below document in table section Under Task module -> Anonymous user section, Remove "Interactions in the meeting chat from Adaptive Card are allowed." and instead of that add "Not Available"
<html>
<body>


User type | Tabs | Bots | Message extensions | Adaptive Cards | Task modules | In-meeting dialog | Meeting stage
-- | -- | -- | -- | -- | -- | -- | --
Anonymous user | Not available | Not available | Not available | Interactions in the meeting chat are allowed. | Interactions in the meeting chat from Adaptive Card are allowed. | Not available | Not available


</body>
</html>

Reference Document-https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/meeting-app-extensibility?tabs=desktop#user-types-in-a-meeting
