### ISSUE TITLE
Does bots registered on Developer Portal Suppports SSO

### ISSUE THREAD

**Issue by osheengithub** [MicrosoftDocs/msteams-docs#6716]
[Enter feedback here]

Since there are 3 different ways to register a BOT, Does the bots registered on the developer portal (bot framework portal) supports SSO.

If yes then can that please be documented

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/47814799/185371646-67b99e19-012a-49b4-bebf-87e53fd0b357.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c68c28-b6d6-ef7e-f8f9-ebebe487378b
* Version Independent ID: c5985867-3795-4280-ef0d-1d66ee30da6e
* Content: [Enable resource-specific consent in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)
* Content Source: [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/graph-api/rsc/resource-specific-consent.md)
* Service: **msteams**
* GitHub Login: @AkJo
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Yes, Bots registered in Developer Portal supports SSO.
Attaching screenshot for reference:
![image](https://user-images.githubusercontent.com/62237649/185379079-60591657-879c-431f-9500-9d9da37bc2e5.png)

@surbhigupta12 - It would be good to document this.

**Comment by osheenkhare** [comment]
is there any documentation around it

**Comment by Prasad-MSFT** [comment]
Its mentioned in this doc(https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/manage-your-apps-in-developer-portal#configure) that, "You can configure your app to authenticate users with single sign-on (SSO)".

**Comment by v-sdhakshina** [comment]
This is addressed as part of revamp of Developer Portal.
PR: https://github.com/MicrosoftDocs/msteams-docs/pull/6446

**Comment by v-shalinirobinson** [comment]
This issue is with regard to the particular scenario of enabling SSO in a bot app. Following a discussion with Dev Portal team, the understanding is that the developer has already configured the bot app and SSO details in Azure AD before coming to Dev Portal. The App ID URI that is configured in Azure AD is added to the app's SSO details in Dev Portal. Dev Portal is not used to configure SSO, but it supports the SSO configuration that is done for a bot app. 
This detailed information will be added to the Bot SSO section as well.
