### ISSUE TITLE
Custom tab is not open in android teams app  

### ISSUE THREAD

**Issue by niteshtatamotors** [MicrosoftDocs/msteams-docs#6746]
I have check previous bug -: https://github.com/MicrosoftDocs/msteams-docs/issues/1335

Previous status -: working fine on ios android web and desktop app
Issue -: Right Now, We are getting issue in only android. tab is not able to load content (simple html content as well).
![image](https://user-images.githubusercontent.com/85864431/186220482-3fe060f9-5526-4396-a3a0-da4532625438.png)
on android 
![image](https://user-images.githubusercontent.com/85864431/186222658-8d7251d2-e47e-4341-98f5-9f65bdec0c9e.png)

I have try with clear storage / update android app / logout / login

**Comment by sayali-MSFT** [comment]
@niteshtatamotors - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@niteshtatamotors -We are not able to repro the issue. It's working fine from our end. Could you please share the manifest json , So that we can try it from our end.
![MicrosoftTeams-image (96)](https://user-images.githubusercontent.com/93527375/186401150-411fa25f-68b7-4382-80c7-503c70db48b0.png)
![MicrosoftTeams-image (95)](https://user-images.githubusercontent.com/93527375/186401155-1dfaf4b9-b1d1-4f6f-ae7a-ae450660edd2.png)
![MicrosoftTeams-image (94)](https://user-images.githubusercontent.com/93527375/186401158-4d0eaa93-257c-47b2-a3ec-82d2e72328e1.png)

**Comment by sayali-MSFT** [comment]
@niteshtatamotors -Did you get chance to check?

**Comment by niteshtatamotors** [comment]
@sayali-MSFT  Issue have been resolved.
It's happened due SSL not install properly. and teams android having strict policy as compare ios and desktop app.(intermediate certificate not install for ssl ) 

Thanks
