### ISSUE TITLE
Worst Documentation and SDK ever 

### ISSUE THREAD

**Issue by IbrahimSam96** [MicrosoftDocs/msteams-docs#6819]
What is this? Generally, I haven't had a problem with SDK's. But this documentation and sdk are complete garbage sorry no offence. Straight trash imho if you have 200+ issues open and can't handle manage and update code

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f629e5c0-0ebe-7beb-8c10-a26fda0b74b2
* Version Independent ID: a1e928cd-ddf1-d134-70f9-34cc236b38db
* Content: [@microsoft/teams-js package - Teams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest)
* Content Source: [nodejs/docs-ref-autogen/@microsoft/teams-js/index.yml](https://github.com/OfficeDev/msteams-client-docs-ref-typescript/blob/live/nodejs/docs-ref-autogen/@microsoft/teams-js/index.yml)
* Service: **msteams**
* GitHub Login: @charlesprakash
* Microsoft Alias: **o365devx**

**Comment by ChetanSharma-msft** [comment]
Hello @IbrahimSam96 - Thanks for share the feedback.
We will check and share your feedback with engineering team accordingly..

**Comment by Wajeed-msft** [comment]
Hello @IbrahimSam96 - Apologies for the inconvenience caused. We would like to understand more so that we could do an RCA and fix the issue. Your feedback is extremely important to us, and we'd request you to please send out an email to [Microsoft Teams Community Help](mailto:microsoftteamsdev@microsoft.com). This will help us setup a quick call with you to discuss this in detail. Looking forward to speaking to you.
