### ISSUE TITLE
What if you want to use the latest manifest schema, but only want to run your app in Teams and not in Office/Outlook?

### ISSUE THREAD

**Issue by JohanKlijn** [MicrosoftDocs/msteams-docs#6950]
What if you want to use the latest manifest schema, but only want to run your app in Teams and not in Office/Outlook?

I ask this question, because we are in the process of validating our app, but it's rejected, because we use manifest version 1.13 and in Office/Outlook our app only shows a message "The App can only be using inside Microsoft Teams.". 

So I think an option to specify in which application (Teams/Office/Outlook) the app can run, would be a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@JohanKlijn - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@JohanKlijn -The Microsoft Teams JavaScript client SDK can help you create hosted experiences in Teams, Office, and Outlook, where your app content is hosted in an [iframe](https://developer.mozilla.org/docs/Web/HTML/Element/iframe).
Starting with version 2.0.0, the existing Teams client SDK (@microsoft/teams-js, or simply TeamsJS) has been refactored to enable [Teams apps to run in Outlook and Office](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview), in addition to Microsoft Teams.
Use the latest TeamsJS (v.2.0 or later) whenever possible, in order to leverage from the latest improvements and new feature support including Teams-only apps. TeamsJS v.1.12 continue to be supported, however, no new features or improvements will be added. The 1.12 and 1.13 schemas are otherwise the same. From a functional perspective, the latest version of TeamsJS supports all existing (v.1.x.x) Teams app functionality while adding the optional ability to host Teams apps in Outlook and Office.
Reference Document-1.https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema
2.https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit

**Comment by JohanKlijn** [comment]
@sayali-MSFT : I know that using the 2.0.0 MS Teams JavaScript client SDK can help me to host the app in Teams, Office and Outlook. So that’s not the issue.

In our case we don’t have any requirement to host the app in Office or Outlook. I know we can downgrade to use the 1.12 app manifest, but that probably in the future we need to update to the latest (because of some change in the app manifest which we require for Teams), and then again we need to support our app in Office and Outlook.

Supporting our app in Office and Outlook, means we also need to test this, which means effort and resources. But in our case it’s “a waste” because our app is really a Teams app, so users will never use it in Outlook or Office. For example upgrading to the latest version > 2..0.0 of the MS Teams JavaScript client SDK, causes already problems, see https://github.com/OfficeDev/TeamsFx/issues/6082.

If our app  only shows the message "The App can only be using inside Microsoft Teams.” In Office or Outlook, Microsoft will not approve the app.

So my issue is, that upgrading to the latest version of the app package manifest, suddenly requires more effort (for example upgrading the SDK, testing in Outlook and Office). So I think a backwards compatible option (to enable the app only in Teams), would make sense.

**Comment by JohanKlijn** [comment]
@sayali-MSFT : FYI, I created an issue on the forum, see https://feedbackportal.microsoft.com/feedback/idea/1f43389b-ca38-ed11-a81b-000d3a7dd504
