### ISSUE TITLE
The portions below are contradictory

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#7064]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/767208/192658820-702d29a7-d71b-4d3c-b825-8aca87d15a70.png">

One says that you can omit userIds.
The other says that userIds property must be included.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47dee5d9-bd9f-f550-8fc2-c2e3b67bba65
* Version Independent ID: 04264d26-1036-342a-e0ea-5edadebc3352
* Content: [Overview of Universal Actions for Adaptive Cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?tabs=mobile)
* Content Source: [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Meghana-MSFT** [comment]
we are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
1. The Teams client automatically invokes refresh calls for all the users if the group or channel has <=60 users hence you can skip userIds in the refresh property if there are <=60 members in Teams group chats or channels.
2. If there are more than 60 members, then automatic refresh results in many concurrent calls to the bot. To avoid this, we must provide the userIds so that the card does not refresh automatically. Refresh option is provided only to users whose Ids have been included. Please note that the size of userIds: [] is 60.
