### ISSUE TITLE
[Doc-enhancement] Blank tab screen troubleshooting step

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7065]
Hi Team,
Blank tab screen will display in following scenario as well:
If the given tab URL is redirecting to login screen, then blank tab will display because Login pages don't render in iFrames, as a safeguard against clickjacking. Your authentication logic needs to use a method other than redirect.

So, please add note in following troubleshooting step:
https://learn.microsoft.com/en-us/microsoftteams/platform/resources/troubleshoot#blank-tab-screen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb80c6db-320c-52b6-f8c4-fad9d146cb24
* Version Independent ID: 37248d85-8023-dd61-e77b-d8571b8d792e
* Content: [Troubleshoot your app - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/troubleshoot)
* Content Source: [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/troubleshoot.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
We will check on it and redirect to doc team accordingly.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document?

Please add the note in below document-

`Note -If the given tab URL is redirecting to login screen, then blank tab will display because Login pages don't render in iFrames, as a safeguard against clickjacking. Your authentication logic needs to use a method other than redirect.`

Document-https://learn.microsoft.com/en-us/microsoftteams/platform/resources/troubleshoot#blank-tab-screen
