### ISSUE TITLE
[Doc-enhancement] State maintenance in Tab application

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7066]
Once user access tab application, based on user action there may be internal navigation and displaying results. But if user navigates away from tab and open tab app again (or click on back button) will show the tab home page. Previous state will not be maintained. This behavior is By design. Adding note in FAQs section will help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61f5ca59-ab3e-b7ef-d3bc-55a88a362abf
* Version Independent ID: 6d43a761-19e0-541e-ba06-170099411ac1
* Content: [Create a personal tab - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-personal-tab)
* Content Source: [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/create-personal-tab.md)
* Service: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
We will look into it and redirect to doc team.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to add this as note ?
**Note:**
`Once user access tab application, based on user action there may be internal navigation and displaying results. But if user navigates away from tab and open tab app again (or click on back button) will show the tab home page. Previous state will not be maintained. This behavior is By design.`
