### ISSUE TITLE
Tab/Bot app display behavior in mobile(iOS/Android)

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7147]
App display behavior is different in mobile but don't see documentation related to it.

For example, Bot messages shows in "Chat" section. Users click on "More" to see the tab app. But the tab app is not showing list. I see it as expected behavior.
![BotScreenshot](https://user-images.githubusercontent.com/69682598/193602704-bd318877-46e1-4acd-aac7-855dacc352b1.png)

If User clicks on "More" in app tray, app is showing in list. So that user can navigate to tab app. And it will have link to open bot as well.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/69682598/193603101-e41e1327-d36c-48fc-bf70-3f7e892f3f43.png)

But this behavior is not documented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5840ee-09e8-93a6-51d8-508eef388b0a
* Version Independent ID: 621a526e-59dd-e81a-ee89-6a714bc055c8
* Content: [Tabs on mobile - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)
* Content Source: [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/design/tabs-mobile.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - Thanks for bringing this up. We are also able to repro this issue/behavior in mobile devices.
@surbhigupta12 - Could you please help here to add this as a note in this doc ?

**Comment by v-spharish** [comment]
@Prasad-MSFT - Can you please provide more details on the "More" options and which one is being referred to? Also please provide the right information to update the context. Thanks.

**Comment by Prasad-MSFT** [comment]
@v-spharish - If one application has 'Bot' and 'Tab' capabilities, in Mobile devices bot messages show in "Chat" section.
 Users click on "More" tab to see the tab app. But the tab app doesn't show in list.
 
![image](https://user-images.githubusercontent.com/62237649/194557323-920214d3-04d6-47b5-bf28-eebffcad3845.png)

But If User clicks on "More" option in app tray (as shown in below screenshot),
![image](https://user-images.githubusercontent.com/62237649/194557799-5034a79c-92c5-43c6-8581-1403240c5e55.png)
 app is showing in list. So that user can navigate to tab app. And it will have link to open bot as well.
 
![image](https://user-images.githubusercontent.com/62237649/194557905-c17d02ac-f447-4605-b397-6ef2ca27f786.png)
