### ISSUE TITLE
Successful/unsuccessful response to Action.Submit is not defined

### ISSUE THREAD

**Issue by aosolis** [MicrosoftDocs/msteams-docs#7299]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/767208/197632037-ce4a7da8-4200-4e00-b7a5-f7003d984886.png">

This section doesn't say which actions it applies to-- I assume Action.Submit in its various forms.

It says what happens when the response is successful or unsuccessful, but doesn't define those terms. What makes a response successful vs unsuccessful?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbc5b84-5be5-b5c4-30c0-58782a748a03
* Version Independent ID: ef6b8aee-52e7-f5d4-7dfa-8f34a1698330
* Content: [Messages in bot conversations - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#adaptive-cards)
* Content Source: [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/conversations/conversation-messages.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Could you please help here to update the documentation?
**Error:** When a response sent to the bot is unsuccessful, `Something went wrong, Try again` message appears.
The error occurs due to various reasons, such as: 
- If there are too many requests
- Due to multiple concurrent operations on the same conversation
- Service dependency issue
- Gateway Timeout etc.
