### ISSUE TITLE
Embedded share to teams is slow

### ISSUE THREAD

**Issue by annaBTI** [MicrosoftDocs/msteams-docs#7436]
The share dialog is slow in coming up, and something with the lag causes the data-href not to properly turn into a link. It sometimes shows as a link, then after a moment goes back to text. ...Sometimes waiting further it becomes a link again, but not always.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c97644a-1a55-0e81-20f5-ea56a8137c7d
* Version Independent ID: 6c97644a-1a55-0e81-20f5-ea56a8137c7d
* Content: [Share to Teams from personal app or tab - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab)
* Content Source: [msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@annaBTI - Thanks for reporting your issue.
We will investigate this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@annaBTI -We are not able to repro the issue, it's working fine from our end.
Microsoft Teams Version 1.5.00.32474 (64-bit). 
Could you please check it once or share a short video, so that we can try to repro it from our end?

https://user-images.githubusercontent.com/93527375/203775009-f50f3cec-4597-46c6-89e5-0193282726dd.mp4
