### ISSUE TITLE
[Doc-enhancement] More details to add about Summary field

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#7632]
Hi Team,
Link to documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#properties-of-the-office-365-connector-card

Developer could not be able to understand the purpose of summary field. Can you add more details about the purpose and usage with screenshots. So that it would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Types of cards - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#properties-of-the-office-365-connector-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - Thanks for your feedback. We will check it and update the document accordingly by providing required information.

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - The details about summary property are already mentioned [here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#additional-information-on-the-office-365-connector-card:~:text=For%20all%20other%20details%20about%20connector%20card%20properties%2C%20see%20actionable%20message%20card%20reference.).
<html>
<body>


summary | String | Required if the card does not contain a text property, otherwise optional. The summary property is typically displayed in the list view in Outlook, as a way to quickly determine what the card is all about.Do always include a summary.Don't include details in the summary. For example, for a Twitter post, a summary might simply read "New tweet from @someuser" without mentioning the content of the tweet itself.
-- | -- | --



</body>
</html>

**Comment by v-silakshmi** [comment]
@Prasad-MSFT The summary property is typically displayed in the list view in Outlook, could you please help us with the behavior in case of Teams. Please advise.

**Comment by Prasad-MSFT** [comment]
@v-silakshmi - You can remove that point in case of MS teams.
