### ISSUE TITLE
No Powershell Example

### ISSUE THREAD

**Issue by thenecroscope** [MicrosoftDocs/msteams-docs#766]
Hi,

I normally use Slack as its Bot service is very easy  to get up and running. Could you provide a Powershell Example of how I can get this "Outgoing webhook" up and running. Micrsoft docs portal is normally very good, seems to fall a bit short here

**Comment by clearab** [comment]
Hi - There is no Powershell support (which would be powered through a Graph API call) for creating outgoing webhooks. You'll need to use the UI to configure one.

You can find the documentation here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/outgoingwebhook

As well as sample applications:
- C#: https://github.com/OfficeDev/microsoft-teams-sample-outgoing-webhook
- Javascript/Node.js: https://github.com/OfficeDev/msteams-samples-outgoing-webhook-nodejs

**Comment by thenecroscope** [comment]
Ideally I was after a simple bot like this:

https://www.powershellgallery.com/packages/SlackBot/

I didn't really want to get involved with lots of other frameworks, just a simple ps script that I can write within a few minutes. Slacks documentation makes this straight forward and it seems easier to get up and running than Teams bots.

**Comment by Trinetra-MSFT** [comment]
Currently there is no PowerShell support for creating Outgoing Webhook.

**Comment by billbliss** [comment]
He's not asking for the ability to _create_ an outgoing webhook using PowerShell. He's asking for an example of how to _respond to messages from an outgoing webhook. 

That's not possible either, however, because we require anything that receives messages - outgoing webhook, bots -- to have an internet-facing https:// endpoint. 

This is a "behind the firewall bots" request but for PowerShell.
