### ISSUE TITLE
How to create custom states apart from user and conversation states in botframework.

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#7682]
I want to store some model data to state apart from user and conversation states. Is it possible to create another state?

**Comment by sayali-MSFT** [comment]
@samthrusha123 - Thanks for reporting your issue.
We will investigate this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@samthrusha123 -[State management](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0#state-management) automates the reading and writing of your bot's state to the underlying storage layer. 
By default, Bot Framework uses the Bot Framework State to store conversation data. 

1. User state
2. Conversation state
3. Private conversation state

If you want directly store data without middleware, you can directly from storage instead of using a state manager. 
You can read and write directly to your storage object without using middleware or context object. This can be appropriate for data your bot uses to preserve a conversation, or data that comes from a source outside your bot's conversation flow. In this data storage model, data is read in directly from storage instead of using a state manager. 
Reference Document-https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#set-up-a-cosmos-db-resource

**Comment by sayali-MSFT** [comment]
@samthrusha123 - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
