### ISSUE TITLE
Update the Step by step by step to support SSO for SingleTenant bots

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8149]
Sample code updates: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/720/files

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26ba02a1-4df6-d09d-309c-552b0a337711
* Version Independent ID: b410630d-3624-e389-480f-ea3307a3b774
* Content: [Build a bot with SSO authentication - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?tutorial-step=4)
* Content Source: [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-bots-with-sso.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 -Please help to update the step-by-step documentation as described below:

1.In [this step](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?tutorial-step=2), at 7.d 
![image](https://user-images.githubusercontent.com/62237649/220613594-dfc79aac-b2af-41e2-81a9-114f281294e2.png)
update the highlighted text to "`Select Type of App as Multi Tenant if your bot is supported on multiple tenants; SingleTenant otherwise.`"

2, In [this step](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?tutorial-step=3), under `To set up Bot service connection` section in second point at marked place update as "`Specify "common" as the Tenant ID. If you are using Single Tenant app registration then set your tenant Id where the bot is registered.`"
![image](https://user-images.githubusercontent.com/62237649/220614932-bfcdc576-0db1-413c-b907-143865e42706.png)

3. In [this step](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?tutorial-step=4), 
![image](https://user-images.githubusercontent.com/62237649/220616856-6769330d-b038-45c7-86c0-1c2cf0550ee6.png)
updatehighlighted text and screenshot as below:

`Select App SSO Sample.sln file from app-sso\csharp folder.`

![image](https://user-images.githubusercontent.com/62237649/220622961-196c5f1a-47a6-4183-888e-eab7b9e750ec.png)

4. For 7th point 
![image](https://user-images.githubusercontent.com/62237649/220624226-50068d9f-bd47-40cb-92bc-c8de94eafcab.png)
update the text and screenshot as below: (Keep the Note as it is)
```
Update the appsettings.json configuration for the bot to use the MicrosoftAppId and MicrosoftAppPassword.
Set MicrosoftAppType as MultiTenant to if your bot is supported on multiple tenants; SingleTenant otherwise.
Set MicrosoftAppTenantId  as common if you are using multi tenant or set your tenantId here if you are using single tenant app registration
Use the OAuth connection name as the Connection Name.
```
![image](https://user-images.githubusercontent.com/62237649/220624908-56422923-5307-45f3-a945-9db3e044597c.png)

5. In [this step](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?tutorial-step=5), update text of 4th point and screenshot of 5th point
![image](https://user-images.githubusercontent.com/62237649/220626064-dc600111-6251-4302-9535-49f4c165fb6b.png)
as below:
`In your cloned repository, go to app-sso > csharp >App SSO Sample > TeamsAppManifest folder.`
![image](https://user-images.githubusercontent.com/62237649/220626557-5f2bd404-4545-43b0-bb81-5d2a3317afa6.png)

6. For 10th point, update the screenshot
![image](https://user-images.githubusercontent.com/62237649/220628153-4a9fc7bd-3bfe-43a0-92e0-1da003b4f7f5.png)
For 11th point, update the screenshot
![image](https://user-images.githubusercontent.com/62237649/220628623-553ed408-e37a-45d2-9fc5-3ec77d0764fe.png)
