### ISSUE TITLE
Issue in example manifest

### ISSUE THREAD

**Issue by Slagethor** [MicrosoftDocs/msteams-docs#8211]
ExampleCmd1 does not match the schema definition. It includes a choices array whilst the inputType property is set to text. From the schema `parameters.choices` description:
_"The choice options for thechoiceset. Use only whenparameter.inputType is choiceset."_

Also, I've tried out the choiceset input type  but that still ends up triggering a text control (might be related).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f94a488-d636-92b3-21eb-c88744c8f272
* Version Independent ID: 7b3413f4-9ade-accf-5cb2-83fead11a32a
* Content: [Manifest schema reference - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema)
* Content Source: [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/resources/schema/manifest-schema.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by sayali-MSFT** [comment]
@Slagethor - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@surbhigupta12 -Could you please help us to update the document.
In the manifest schema json, goto composeExtensions --> ExampleCmd1 section 
instead of "inputType": "text" add "inputType": "choiceset".

Document Link- https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#sample-full-manifest
