### ISSUE TITLE
How to create user token from teams bot for the api call 

### ISSUE THREAD

**Issue by samthrusha123** [MicrosoftDocs/msteams-docs#8348]

**Comment by samthrusha123** [comment]
When user logins first time it will create one token right. How can we generate that token again whenever we want?

**Comment by sayali-MSFT** [comment]
@samthrusha123 -To communicate with the Bot Connector service, you must specify an access token in the Authorization.
Request an [access token](https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0&tabs=multitenant#step-2-obtain-the-jwt-token-from-the-the-azure-ad-v2-account-login-service-response) based on your bot's application type-

- As a user-assigned managed identity, so that you don't need to manage the bot's credentials yourself.
- As a single-tenant app.
- As a multi-tenant app.

Multitenant-
```
POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=MICROSOFT-APP-ID&client_secret=MICROSOFT-APP-PASSWORD&scope=https%3A%2F%2Fapi.botframework.com%2F.default
```

The app can use the [refresh token](https://learn.microsoft.com/en-us/graph/auth-v2-user#authentication-and-authorization-steps) to get a new access token when the current one expires.

```
https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?
client_id=11111111-1111-1111-1111-111111111111
&response_type=code
&redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F
&response_mode=query
&scope=offline_access%20user.read%20mail.read
&state=12345
```
