### ISSUE TITLE
Found that if an additional language, has too long a Short Description, then Developer Portal fails to update the app

### ISSUE THREAD

**Issue by gsheeley** [MicrosoftDocs/msteams-docs#8529]
Teams App - Developer Portal - Add Languages - Fails to update‎

We have created a simple app using the Developer Portal. 
We have updated the app a number of times. 
However, whenever we add Languages to support French, and click the "Submit app update", nothing happens. 
If I then remove the additional language and click "Submit app update" it submits it to the Teams Admin centre as it should.

We have tested both these against https://dev.teams.microsoft.com/appvalidation.html verification tool and they both pass. 
 I have tested adding the app directly to the Teams Admin Centre and it too fails. 

When we amended the French language for the Short Description, to be even shorter, it then worked, i.e. 
From "Adoption de nouvelles façons de travailler"
To "Adoption de nouvelles façons de travailler avec le programme Un espace de travail"

Just letting others know until, either support is added or the validation tools pick this up as an issue.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and update you.

**Comment by Meghana-MSFT** [comment]
This is because your short description has 81 chars, but it should not exceed 80 chars. That is the reason it is working after making the Short Description even shorter.
![image](https://user-images.githubusercontent.com/81138249/234525693-cd1124a2-c8a7-4362-886e-ab81fe267c5a.png)


However, it should give error in app validation. We tried adding French language with the short description that you have shared. It gives below error. 

![image](https://user-images.githubusercontent.com/81138249/234525449-e44f336e-1b5d-44a6-a79f-309e9b70f9ee.png)

Could you please share your app package with us, so that we can check this at our end as well. Thanks!
