### ISSUE TITLE
Typo error `aud1`

### ISSUE THREAD

**Issue by yuezk** [MicrosoftDocs/msteams-docs#8600]
<img width="762" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3297602/2ff4e564-e910-43a5-94ae-570c5f900c6b">

Questions:

- What `this value` represents?
- `aud1` instead of `aud`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 410609cf-c930-72de-319d-351212f71b8c
* Version Independent ID: 410609cf-c930-72de-319d-351212f71b8c
* Content: [Code configuration for enabling SSO for tabs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code)
* Content Source: [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/authentication/tab-sso-code.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Nivedipa-MSFT** [comment]
@yuezk - Thanks for reporting your issue. We will confirm this value with engineering team and will update the content accordingly.

**Comment by Nivedipa-MSFT** [comment]
@yuezk - This value refer to the 'https://login.microsoftonline.com'. And it is aud instead of aud1.
For more information, could you please refer  [Validate tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validate-tokens) document.

@surbhigupta12 - Could you please delete the whole content from [this ](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code#validate-the-access-token)section and add following content in this section.

**For details about validate the access token, see [Validate tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validate-tokens).**

**Comment by Nivedipa-MSFT** [comment]
@yuezk - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.

**Comment by yuezk** [comment]
Done
