### ISSUE TITLE
How to properly close a task module after submit to a bot?

### ISSUE THREAD

**Issue by jl0zano** [MicrosoftDocs/msteams-docs#8797]
We're experiencing issues related to when submit a task module to a bot.

We're using a React Tabs app. We open a task module using

`
teams.dialog.url.bot.open(
  {
    "title": "Edit Your Story",
    "url": "our-react-url",
    "completionBotId": "our-bot-id",
    "size": {
        "height": 700,
        "width": 600
    }
  }
);
`

Then, after we save relevant info in our back end, the bot returns

`
return {
  task: {
    value: "",
    type: "message",
  },
} as TaskModuleResponse
`

which works on iOS and Desktop but displays an extra empty pop-up on Android which is annoying.

How do we properly return a response that just closes a task module? We don't want to reply with an adaptive card or a continuation to another task module.

Thanks.

**Comment by sayali-MSFT** [comment]
@jl0zano - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@jl0zano -We have tried with the below code to close the task module-
Are you looking for the same?

```
 async handleTeamsTaskModuleSubmit(context, taskModuleRequest) {
  
        await context.sendActivity(MessageFactory.text('handleTeamsTaskModuleSubmit: ' + JSON.stringify(taskModuleRequest.data)));       
        return null;
    }
```


https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/9fe6353c-7dab-479d-b4d1-73887e90ec9e

 if your issue is not resolve using above code, please share a short video or screenshots, so that we can investigate further from our end.
 
 Reference sample-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-task-module/nodejs

**Comment by jl0zano** [comment]
@sayali-MSFT Thanks for your response. Returning null worked! It would be ideal to have this in the documentation:

https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs#responds-to-the-tasksubmit-messages

When we were not returning anything the task modules were acting weird on iOS for some reason. Returning null worked.

**Comment by sayali-MSFT** [comment]
@jl0zano - Glad to hear that your issue is resolved. We will update the document accordingly.
Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
