### ISSUE TITLE
IndexedDB is not possible with the mobile version of Teams Applications

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8817]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/8583 

**Details from original post:**
IndexedDB isn't possible on the phone, and I was using it with an encryption. What is the alternative for phones?
It looks like I'm not the only one with this issue either: https://techcommunity.microsoft.com/t5/microsoft-teams/indexeddb-is-not-working-in-the-android-app-for-teams/m-p/1359784---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by Nivedipa-MSFT** [comment]
@wrharper-AASP - Thanks for reporting your issue. We are checking this with engineering team. We will let you know once we get any updates on it.

**Comment by wrharper-AASP** [comment]
It turns out this is actually worse than I thought.
Teams App version appears to hang during info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
loading time: 60697
Due to my error checking, it will "eventually" continue and not use IndexedDB. For some reason it hangs for far too long though just by trying an IndexedDB call.

How can we properly cache inside of the Teams App? There must be a way because if you have a large app with tons of server-side things going on, you won't be able to maintain a large user base...

What are the header differences between the app, mobiles, and browsers? How can we determine no user agent cross overs?

I would like to (at least for now) make the app ignore IndexedDB if it is running inside of the Microsoft Teams App.

**Comment by wrharper-AASP** [comment]
I would like to add this happens on the Desktop version for testing. Not the mobile version because it is harder to test that one. I assume the issue is the same though. Edge and Chrome appear to work fine, I have not tested anything else. This is indeed a problem with the Microsoft Teams Application (both Desktop & Mobile) only.

**Comment by wrharper-AASP** [comment]
I was able to detect this by determining if it is a mobile OS first and then just had to look if the user agent had "Teams/" on desktop apps. This appears to be possible now, but this is a "no cache mode" which can be heavy on the server.

**Comment by Nivedipa-MSFT** [comment]
@wrharper-AASP - It seems that you are experiencing a hang issue in the Teams App, particularly related to IndexedDB. Caching within the Teams App can be achieved using different mechanisms, such as browser cache, service workers, or other client-side caching techniques. However, it's important to note that the behavior may vary depending on the platform (app, mobile, or browser) and the specific headers involved.

To determine user agent differences and avoid any cross-overs, you can inspect the request headers sent by the client. The "User-Agent" header provides information about the client's platform, browser, and version. You can use this header to differentiate between the Teams App, mobile devices, and browsers.

Regarding your specific request to ignore IndexedDB if running inside the Microsoft Teams App, you can check the user agent in your code and conditionally skip any IndexedDB-related logic. You can obtain the user agent string from the request headers and compare it to the known user agent strings for the Teams App.

If you have any further questions or need additional assistance, feel free to ask.

**Comment by wrharper-AASP** [comment]
Right, the idea is to be able to use IndexedDB everywhere instead of just certain things. There appears to be no way to cache in Teams Apps in general from what I have been reading. This was a suggestion to fix that problem.

**Comment by Nivedipa-MSFT** [comment]
@wrharper-AASP - Could you please raise a [feature request](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472) for adding cache functionality in Teams

**Comment by wrharper-AASP** [comment]
It's for Teams Developer Apps specifically, not the original Teams App itself. This is only a problem in the "Apps" tab when you create your own App, there is no way to cache. Because there is a disconnect from Developers making Teams App and the Microsoft Teams App itself.
