### ISSUE TITLE
Unexpected behaviour with app created from App Studio

### ISSUE THREAD

**Issue by Bryand13** [MicrosoftDocs/msteams-docs#890]
Hi there,

We have an unexpected behaviour with an app created from App Studio. In a tab, when is add a web page, it does not visualize correctly, while if the page is configured in a random tab in MS Teams, the page is looking fine.

Making the debug in a browser, we see the following message:
Refused to display 'https://ferroxx.xxxxx..com/adfs/ls/idpinitiatedsignon.aspx?logintoRP=https://hana.ondemand.com/xxxxxxxxx' in a frame because it set 'X-Frame-Options' to 'deny'
![MSTeams_ChatBot](https://user-images.githubusercontent.com/50946094/63158751-415ff080-c01a-11e9-801f-226bc3d927eb.png)

Configuration for tab:
![MSTeams_ChatBot2](https://user-images.githubusercontent.com/50946094/63159146-188c2b00-c01b-11e9-9304-d51094b8b757.png)

And when the page is trying to load inside the app: KO
![MSTeams_ChatBot3](https://user-images.githubusercontent.com/50946094/63159719-766d4280-c01c-11e9-8bc3-c99bb8465827.png)

And when is loaded in a random tab: OK
![MSTeams_ChatBot4](https://user-images.githubusercontent.com/50946094/63159843-a583b400-c01c-11e9-9ec2-f95908b7b232.png)

I did open a ticket with Microsoft but there were no solution, because App Studio is not supported.

Appreciate your comments
Thanks in advance

**Comment by clearab** [comment]
I don't believe this has anything to do with app studio. It looks like you're trying to just add your sign-in page as an app. However, the process for creating custom tabs is a bit more involved than that. See:

- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview
- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-aad

**Comment by Bryand13** [comment]
> I don't believe this has anything to do with app studio. It looks like you're trying to just add your sign-in page as an app. However, the process for creating custom tabs is a bit more involved than that. See:
> 
> * https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-overview
> * https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-tab-aad

Hi clearab,
Thank you very much for the info.

But indeed, as you said I'm just trying to add a webpage sign-in in a app, the webpage is: "https://www.chatxxxxx.com" -> this page is redirected to our adfs page sign-in.

The "problem" is that, i'm able to visualize and sign-in the page in a random tab, unlike with the customized app.So, do you know why this is happening?

**Comment by clearab** [comment]
My apologies for not being clearer. Adding a website to a tab and creating an app that contains a custom tab are two fairly different things. Creating a custom tab involves adding the Teams JavaScript SDK to the hosted content page and using that SDK to communicate with Teams. Authentication in custom tabs is different than a regular webpage (the link I provided above outlines the details).

Adding a website tab on the other hand just embeds the URL you provide in a webview. It cannot communicate with Teams, and there are no expectations on behavior.

Essentially, you cannot just add any URL to a custom tab in an app. You have to customize that page in order to work as part of an app. Please take a look at the linked documentation I provided above.

If there is a particular scenario you're trying to complete, please let me know what that is and I could possibly help with ways of achieving your goal.

**Comment by Bryand13** [comment]
Hi clearab,

Thank you so much for the information and explanation. So, now we know that we have to customized the page that we want to host in MS Teams. The page is the followign one: https://chatbot-ehuak7dmhc.dispatcher.hana.ondemand.com/index.html?hc_reset --> who it's redirect to --> https://ferrofs.ferrovial.com/adfs/ls/idpinitiatedsignon.aspx?logintoRP=https://hana.ondemand.com/ehuak7dmhc

Do you see any problem to implement it on MS Teams as a tab?

Thanks in advance!

**Comment by clearab** [comment]
Yes, that will not work. Please see the documentation I linked above concerning how AAD authentication works in a custom tab in a Teams app.
