### ISSUE TITLE
[Doc-bug] Microsoft 365 portal - Teams extended apps are not displaying to users in Microsoft 365 portal

### ISSUE THREAD

**Issue by SubbaReddi** [MicrosoftDocs/msteams-docs#8901]
Teams apps extended to Microsoft 365 can be hidden/displayed to users using setting in Microsoft 365 admin portal. 
It can be configured in Microsoft 365 admin portal -> Settings(in left navigation) -> Integrated apps -> Available apps -> Settings icon -> Change dropdown value in "Who can access apps in your tenant?".

But the same information is not available in documentation. So, please add the same. 

Screenshots for reference: 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/69682598/659729b3-ea5c-4ae8-b6a1-698939b47644)
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/69682598/9cb03217-4a3d-4187-9e63-473138dee42a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Version Independent ID: b2cf31a5-621a-eeac-26c9-89ada49466c0
* Content: [Extend a Teams personal tab app across Microsoft 365 - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit)
* Content Source: [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md)
* Service: **msteams**
* Sub-service: **m365apps**
* GitHub Login: @erikadoyle
* Microsoft Alias: **mosdevdocs**

**Comment by ChetanSharma-msft** [comment]
Hello @SubbaReddi - Thanks for raising this issue.
We will look into it and redirect to doc team.

**Comment by surbhigupta12** [comment]
@erikadoyle, could you please look into this.

**Comment by Meghana-MSFT** [comment]
@erikadoyle -  Could you please help here?

**Comment by erikadoyle** [comment]
As these are admin settings, the requested content would belong in the IT Admin docs, rather than here in Developer. And actually this setting is already documented there: https://learn.microsoft.com/microsoft-365/admin/manage/teams-apps-work-on-outlook-and-m365#manage-how-users-can-install-teams-apps-on-outlook-and-the-microsoft-365-app

We do link to admin docs from developer docs (from [extended Teams apps](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview) overview):

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/2170770/3671e36e-f599-4604-9bbc-b53615ea5d49)

. . . but maybe it would be helpful to make the link more prominent. Will post a PR for that shortly--
