### ISSUE TITLE
The status code returns 200 but the message cannot be sent to Teams.

### ISSUE THREAD

**Issue by hckt2022** [MicrosoftDocs/msteams-docs#8999]
I sent a message using webhook in python,
The status code returns 200 but the message cannot be sent to Teams. What could be the problem?

The code is as follows: 

import pymsteams

url = 'https://xxx.webhook.office.com/webhookb2/xxx'
myTeamsMessage = pymsteams.connectorcard(url)
myTeamsMessage.title("Test Title")
myTeamsMessage.text("Test Message from python")
myTeamsMessage.send()
last_status_code = myTeamsMessage.last_http_response.status_code
print(last_status_code)

**Comment by Meghana-MSFT** [comment]
@hckt2022 - We ran the script you have shared. It returned 200 and card is posted as well.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/766876c4-7d00-41b3-b108-1c71b5704ceb)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/c8816658-d6d1-4b4e-9b4d-e4e22c68284a)

Could you please more details so that we can repro this issue? How are you running the script?

**Comment by hckt2022** [comment]
Run the code in visual studio code.
![001](https://github.com/MicrosoftDocs/msteams-docs/assets/109566355/b1719096-8a78-45f4-8d47-37efac7b939f)

Sent messages are not displayed in the Teams desktop application.
![002](https://github.com/MicrosoftDocs/msteams-docs/assets/109566355/60fce2b0-4644-434c-89a8-7e98818878f4)

**Comment by Meghana-MSFT** [comment]
@hckt2022 - 
Its working fine from visual code studio as well. 

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/ee54c8b4-912e-4e9d-97e0-9193a61cc6bb)

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/05d46b3e-75a2-49a5-9d45-896699e5ceb9)


Could you please try sending messages via other methods so that we can check if it is an issue with VS code or webhook.
https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-messages-using-curl-and-powershell

**Comment by hckt2022** [comment]
This is the result of a curl and powershell run.
![a01](https://github.com/MicrosoftDocs/msteams-docs/assets/109566355/5a5fc42c-b617-4217-a4b4-7bbca221c6d5)
![a02](https://github.com/MicrosoftDocs/msteams-docs/assets/109566355/8e74346e-3592-4df7-8a53-7d86c53b79c2)

**Comment by Meghana-MSFT** [comment]
@hckt2022 - Is the message sent to Teams while using CURL and powershell?

**Comment by hckt2022** [comment]
Both when I used CURL and powershell, I was able to receive messages in Teams.

**Comment by Meghana-MSFT** [comment]
@hckt2022 - Thank you, just to confirm again messages sent via Python are still not sent in Teams?

**Comment by hckt2022** [comment]
Yes, messages sent via python get a status code of 200 but are not reflected in Teams.

**Comment by Meghana-MSFT** [comment]
Thank you for the confirmation. We will check this internally and get back to you.

**Comment by Meghana-MSFT** [comment]
@hckt2022 - pymsteams is not a supported library from Microsoft, its a 3p library. As a workaround can you please try and use without pymsteams and see if that works.

**Comment by Meghana-MSFT** [comment]
@Karpisek - The same issue has been reported here - https://github.com/MicrosoftDocs/msteams-docs/issues/9064.
