### ISSUE TITLE
"You should treat the identity-related information in the tab context simply as hints and validate them before use."

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#929]
Is it possible to better explain, at least high-level, what this means: "You should treat the identity-related information in the tab context simply as hints and validate them before use."? What should we be validating, and in what way?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22c5f1eb-f67b-5ecd-b417-644f6476e2e1
* Version Independent ID: b0e0fd61-53d8-ae68-335f-3279fd925673
* Content: [Authentication flow for tabs - Teams](https://docs.microsoft.com/en-gb/microsoftteams/platform/concepts/authentication/auth-flow-tab)
* Content Source: [msteams-platform/concepts/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/authentication/auth-flow-tab.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by clearab** [comment]
This is just saying that you shouldn't assume that the personal identification information included in the getContext call should not be used for authentication or authorization purposes. You need to prompt the user to actually log in for that. Otherwise you are opening yourself to a man in the middle attack.
