### ISSUE TITLE
Error in creating app from App Studio

### ISSUE THREAD

**Issue by deepak-gaddi** [MicrosoftDocs/msteams-docs#955]
![image](https://user-images.githubusercontent.com/40228239/65035093-fc571300-d965-11e9-9ece-747bfc660ee9.png)

**Comment by deepak-gaddi** [comment]
Is this an issue with my network/firewall?

**Comment by MattSFT** [comment]
Generally this means that you are not able to access the API due to a connection issue. It is likely that the UI piece was cached on your computer and possible that network was interrupted when trying to fetch data.

Also, if you have never been able to use App Studio before, it is possible you have some network or firewall rule blocking connections to the App Studio API.

**Comment by deepak-gaddi** [comment]
Thank you, yes it's firewall issue. I'm able to work by connecting to VPN from office network. It works perfectly fine with home network.
