### ISSUE TITLE
Azure App Service Authentication blocked by Microsoft Team SSO in Personal tab 

### ISSUE THREAD

**Issue by ablack34** [MicrosoftDocs/msteams-docs#9830]
Hi,

I have a custom app hosted in an Azure App Service that has the app service authentication enabled and identity provider set to Microsoft. I want this application be a Teams personal Tab app and I am using the Teams Toolkit to do so. The authentication works in the browser if I just use the app service URL. In Teams, when I try to access my application and click on the login page the login popup is prevented from opening with an error like the screenshot below. 

<img width="424" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/90779303/9063fd94-0f50-4de5-b773-ac0605863d04">

How can I allow the popup to be allowed in Teams?

It is worth noting that so far I have not added any custom code for authentication so far.

**Comment by Prasad-MSFT** [comment]
@ablack34 - This error is due to the fact that Azure AD doesn't allow its content to be placed in an iframe. This is a security measure to prevent clickjacking attacks. In Teams, your app is loaded in an iframe, hence the error.
To resolve this, you need to add a pop-up page to host the identity provider. You can use the `authentication.authenticate()` function of the TeamsJS library to launch this page when the button is selected.
```
import { authentication } from "@microsoft/teams-js";
authentication.authenticate({
url: window.location.origin + "/tab/simple-start-v2",
width: 600,
height: 535})
.then((result) => {
console.log("Login succeeded: " + result);
let data = localStorage.getItem(result);
localStorage.removeItem(result);
let tokenResult = JSON.parse(data);
showIdTokenAndClaims(tokenResult.idToken);
getUserProfile(tokenResult.accessToken);
})
.catch((reason) => {
console.log("Login failed: " + reason);
handleAuthError(reason);
});
```

In this example,` /tab/simple-start-v2` is the start page of the authentication flow. This should match what you registered in the Azure AD Application Registration Portal.
Please note that the authentication flow must start on a page that's on your domain. This domain should also be listed in the `validDomains` section of the manifest. Failure to do so will result in an empty pop-up.
Also, failing to use `authenticate()` will cause a problem with the pop-up not closing at the end of the sign-in process.

**Comment by ablack34** [comment]
Hey,

Thank you, this makes sense. I'm a bit lost in where this code should go? Should it be in my custom web app or in the Teams App project that has the manifest file etc?

**Comment by Prasad-MSFT** [comment]
> Hey,
> 
> Thank you, this makes sense. I'm a bit lost in where this code should go? Should it be in my custom web app or in the Teams App project that has the manifest file etc?

The code you've mentioned is used for authentication in a Teams app and should be placed in your custom web app that is part of your Teams App project.
This code uses the Teams JavaScript client SDK to initiate the authentication process when a certain action is performed, such as clicking a button. The authentication.authenticate() function opens a pop-up window to the specified URL (/tab/simple-start-v2 in this case), which should be a page in your web app that handles the authentication process.
