### ISSUE TITLE
User Agent doesn't contain Teams word

### ISSUE THREAD

**Issue by savissamsetti** [MicrosoftDocs/msteams-docs#9967]
We are relying on UserAgent to identify if the Teams app is used in Browser or using a desktop version. But with the new version of Teams, user agent got changed and we are not able to differentiate these 2 from our custom app. Please provide us a way to identify the Browser version and Desktop version from the Custom App personal and Custom tabs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19ddf42e-0a47-7717-52d4-e549155480a2
* Version Independent ID: 4bbe9beb-233f-cfd5-097b-f280aab5fde8
* Content: [Microsoft Teams developer community support and feedback - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/feedback)
* Content Source: [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/feedback.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by ChetanSharma-msft** [comment]
Hello @savissamsetti - Thanks for raising your query.
Could you please confirm whether you are developing Teams apps using this documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/mstdd-landing

Also, please let us know how you are using User Agent to get the details including the repro steps.

**Comment by Meghana-MSFT** [comment]
You can get these values inside app.host.clientType in Tab context. It returns the type of host client. Possible values are android, ios, web, desktop, surfaceHub, teamsRoomsAndroid, teamsPhones etc - https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2%2Cdefault#get-context-by-using-the-microsoft-teams-javascript-library:~:text=host%22%3A%20%7B%0A%20%20%20%20%20%22-,clientType,-%22%3A%20%22The

**Comment by WGroenestein** [comment]
> You can get these values inside app.host.clientType in Tab context. It returns the type of host client. Possible values are android, ios, web, desktop, surfaceHub, teamsRoomsAndroid, teamsPhones etc - https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2%2Cdefault#get-context-by-using-the-microsoft-teams-javascript-library:~:text=host%22%3A%20%7B%0A%20%20%20%20%20%22-,clientType,-%22%3A%20%22The

Is there an alternative available (like it used to be using the user agent in the "old" client) which does not include including an entire JS dependency which needs to be loaded on each page. The reason I'm asking is that we have a single web application both for the browser and to be "embedded" as Teams app (i.e. they use the same urls). This works great for all clients except the "new" desktop client. The reason we need to know if the application is hosted in a Teams client is to select a strategy to open new windows (window.open). The reason we have different strategies is that we have a mechanism in place to prevent window hijacking (referrer/opener) which doesn't work when hosted in a Teams client due to the nature of how the Teams client implements the opening of new windows.
