### ISSUE TITLE
Challenges on API Endpoints for Bot Installation and Threaded Reply in Teams

### ISSUE THREAD

**Issue by v-preethah** [MicrosoftDocs/msteams-docs#9971]
**Feedback**
There's a plethora of information available it's overwhelming for a new person, but got used to it with experience. And had trouble finding niche information until we encountered them live.
Examples -
Bot installation to group chat was sending an event with some details, whereas bot installation to a channel api was only sending 201 created event without any details.
Threaded reply - Spent few days searching for the API for replying in a thread, wasn't able to pinpoint it in documentation. Found it on a stack overflow answer.
Took so much time to understand how to send a message in the teams app like a bot. Understood bot framework endpoints have to be used after a very long time.
I personally felt that the documentation is friendly for SDKs, but if we're using the API endpoints, we did run into issues.
I remember only a couple at the top off my head, but there were quite a lot of other issues as well, which we found only when implementing the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d3bb613-220a-58f0-f819-a375031e5447
* Version Independent ID: ea94ec58-4911-1596-e7fe-9af6b59a2f0f
* Content: [Bots and SDKs - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/bot-features?tabs=dotnet)
* Content Source: [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/bot-features.md)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **anclear**

**Comment by Prasad-MSFT** [comment]
Thanks @v-preethah for raising this. We will do analysis on it and will take appropriate measures.

**Comment by Prasad-MSFT** [comment]
1. There is no Graph endpoint to add a bot to a Group chat, only personal and Teams channels are available.
https://learn.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http#example-1-install-an-app-for-a-user
https://learn.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&tabs=http#request
This is by design to get `HTTP/1.1 201 Created` response without any details.

2.Reply to any message in channel is documented here:
https://learn.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&tabs=http

**Comment by v-preethah** [comment]
Hi @Prasad-MSFT

Please let us know if there are any doc updates required. Thank you!

**Comment by Prasad-MSFT** [comment]
Hi @v-preethah - There is no doc update required. The asked details are already there in documentation.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
